config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  devise_scope :user do
    get 'users/sign_out(.:format)', to: 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin_portal', as: 'rails_admin'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :storage_items, only: [:index, :edit, :update]
  resources :delivery_requests, :pickup_requests, only: [:show, :create, :new, :edit, :update, :destroy]
  resources :subscribers, only: [:create]

  get 'admin/block_time', to: 'admin_pages#block_time', as: 'block_time'
  post 'admin/block_time', to: 'admin_pages#create_block_time'
  get 'admin', to: 'admin_pages#admin', as: 'admin'
  get 'admin/record_pickup_request/:id', to: 'admin_pages#record_pickup_request', as: 'admin_record_pickup_request'
  get 'admin/record_delivery_request/:id', to: 'admin_pages#record_delivery_request', as: 'admin_record_delivery_request'
  patch 'admin/record_pickup_request/:id', to: 'admin_pages#save_changes_pickup_request'
  patch 'admin/record_delivery_request/:id', to: 'admin_pages#save_changes_delivery_request'
  get 'admin/assign_driver/:id', to: 'admin_pages#assign_driver', as: 'admin_assign_driver'
  post 'admin/assign_driver/:id', to: 'admin_pages#update_assign_driver'
  patch 'admin/complete_packing_supplies_request/:id', to: 'admin_pages#complete_packing_supplies_request', as: 'complete_packing_supplies_request'
  patch 'admin/complete_pickup_request/:id', to: 'admin_pages#complete_pickup_request', as: 'complete_pickup_request'
  patch 'admin/complete_delivery_request/:id', to: 'admin_pages#complete_delivery_request', as: 'complete_delivery_request'
  get 'admin/sign_in_as_user', to: 'admin_pages#sign_in_as_user', as: 'admin_sign_in_as_user'
  post 'admin/sign_in_as_user' => 'admin_pages#post_sign_in_as_user'

  get '404', to: 'static_pages#not_found', as: 'not_found'
  get '422', to: 'static_pages#server_error'
  get '500', to: 'static_pages#server_error', as: 'server_error'

  get 'new-city' =>'static_pages#new-city'
  get 'national' =>'static_pages#national'
  get 'premium-on-demand-luxury-moving-storage' => 'static_pages#luxury'
  get 'moving-and-storage-on-demand' => 'static_pages#moving_and_storage'
  get 'storage-garage-organization' => 'static_pages#garage_organization'
  get 'cu-student-storage' => 'static_pages#cu_student_storage'
  get 'cheap-storage' => 'static_pages#cheap_storage'
  get 'storage-savings-colorado' => 'static_pages#landing_page_1'
  get 'cu-student-storage-2' => 'static_pages#landing_page_2'
  get 'moving-and-storage-on-demand-denver-boulder' => 'static_pages#landing_page_3'
  get 'premium-on-demand-luxury-moving-storage-2' => 'static_pages#landing_page_4'
  get 'storage-garage-organization-2' => 'static_pages#landing_page_5'
  get 'apartment' => 'static_pages#moving_and_storage'
  get 'student' => 'static_pages#cu_student_storage'

  get 'about', to: 'static_pages#about', as: 'about'
  get 'feedback', to: 'static_pages#feedback', as: 'feedback'
  get 'faq', to: 'static_pages#faq', as: 'faq'
  get 'contact' => 'static_pages#contact'
  get 'email' => 'static_pages#email_example'
  get 'terms-of-service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get 'storage-service-tos', to: 'static_pages#storage_service_tos', as: 'storage_service_tos'
  get 'privacy-policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'users/referral', to: 'users#referral', as: 'users_referral'
  get 'how-quickbox-works', to: 'static_pages#how_quickbox_works', as: 'how_quickbox_works'
  get 'pricing', to: 'static_pages#pricing', as: 'pricing'
  get 'locations/boulder-colorado' => 'static_pages#boulder'
  get 'locations/denver-colorado' => 'static_pages#denver'

  get 'signup', to: 'signup_pages#select_items', as: 'new_signup_pages'
  post 'signup', to: 'signup_pages#post_select_items'
  post 'signup/create_login', to: 'signup_pages#create', as: 'signup_create_login'
  get 'signup/add_payment', to: 'signup_pages#show', as: 'signup_add_payment'
  patch 'signup/add_payment', to: 'signup_pages#add_payment'

  root 'static_pages#homepage'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def homepage
		@subscriber = Subscriber.new
	end

	def about
		@user = current_user
	end

	def contact
		@user = current_user
	end

	def faq
		@user = current_user
	end

	def feedback
		@user = current_user
	end

	def not_found
		render status: 404
	end

	def server_error
		render status: 500
	end

	def national
		@subscriber = Subscriber.new
	end

	def luxury
		@subscriber = Subscriber.new
	end

	def moving_and_storage
		@subscriber = Subscriber.new
	end

	def garage_organization
		@subscriber = Subscriber.new
	end

	def cu_student_storage
		@subscriber = Subscriber.new
	end

	def cheap_storage
		@subscriber = Subscriber.new
	end

	private

	def no_ready_users!
		redirect_to storage_items_url and return if current_user and current_user.ready?
	end
end

app/views/static_pages/althome.html.haml
- content_for :title do
  = "Homepage |"
= render :partial => 'partials/althome_header'
= javascript_include_tag "new_homepage"

/ %p= link_to 'Login', new_user_session_path
#homepage.align-center

  // First Page
  %section#introSection.align-center
    #introSectionContentWrapper
      %h1.no-margin
        %span.blue QuickBox
        Storage
      %h3.dark-gray
        You Pack.
        %span.blue We Pickup.
      %br/
      %br/
      .main-images.full-width.row
        .col-md-4.col-sm-4.no-padding
          %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/home-notext-1.png", :alt => ""}/
          %p Flexible Pricing By The Item
          / .blue-bar
        .col-md-4.col-sm-4.no-padding
          %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/home-notext-3.png", :alt => ""}/
          %p Door To Door Pickup & Delivery

        .col-md-4.col-sm-4.no-padding
          %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/home-notext-2.png", :alt => ""}/
          %p Your Items A Click Away
          / .blue-bar

      %br/
      %br/

      .slider-wrapper.hidden
        %ul.bxslider
          %li
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/homepage-1.png", :alt => ""}/
          %li
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/homepage-2.png", :alt => ""}/
          %li
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/homepage-3.png", :alt => ""}/
        %img{:src => "", :alt => ""}/
      %br/
      %div
        %h3.heavy-font.dark-gray
          Ready To Go?
          = link_to "Schedule a free pickup!", new_signup_pages_path

          %p
            (or call us at
            %span 720-583-5826
            )

  // Divider Blue Bar
  .blue-bar#signup-about
    .tab.pull-right
      %h5.white How Do Pickups Work?
    %br/
    %h2.white Door To Door Storage?


  // Pickup and Delivery Process Section
  %section.pickup-delivery-process.container
    %br/
    %br/
    %br/
    %br/
    %br/
    %h3.dark-gray.no-margin
      We Offer
      %span.blue Free Pickups
    / %h2.no-margin
    /   %span.blue Quickbox
    /   Pickups
    %hr.half-width.half-opacity
    .container
      %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/pickup-process.png", :alt => ""}/
    %br/
    %br/

    %br/
    %br/
    / %h3.dark-gray.no-margin
    /   And
    /   %span.blue Convenient Deliveries
    /   %hr.half-width.half-opacity
    / .container
    /   %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/delivery-process.png", :alt => ""}/
    / %br/
    / %br/
    / %br/
    / %br/

  // Pricing Section
  .blue-bar#signup-pricing
    %br/
    %h2.white What About Pricing?
    %br/
  %br/
  %br/
  %br/
  %br/
  %section
    .container.row.pricing-wrapper
      %h3.dark-gray.no-margin
        %span.blue Flexible Pricing
        By The Item
      %hr.width-80.half-opacity
      .col-md-4.pricing-block
        %i.pricing-icon.icon-icon-box
        .pricing-info
          .pricing-title.by-item
            %h3 Small Items
          .price
            %h3.dark-gray $5.00
            %p.price-subtext per month
          .price-description
            %p Items like boxes (3 cubic feet), tires, bags, or similarly sized objects.
      .col-md-4.pricing-block
        %i.pricing-icon.icon-icon-bike
        .pricing-info
          .pricing-title.by-item
            %h3 Medium Items
          .price
            %h3.dark-gray $12.00
            %p.price-subtext per month
          .price-description
            %p Items like bikes, chairs, skis, luggage, coffee tables, bed-side, tables.
      .col-md-4.pricing-block
        %i.pricing-icon.icon-icon-couch
        .pricing-info
          .pricing-title.by-item
            %h3 Large Items
          .price
            %h3.dark-gray $25.00
            %p.price-subtext per month
          .price-description
            %p Items like couches, mattresses, desks, dressers, chests, bed frames.
    %br/
    %br/
    / %br/
    / %br/


    / .container.row.pricing-wrapper

    /   %h3.dark-gray.no-margin
    /     %span.green Traditional Pricing
    /     By The Space
    /   %hr.width-80.half-opacity

    /   .col-md-4.pricing-block
    /     %i.pricing-icon.icon-5x10.by-space
    /     .pricing-info
    /       .pricing-title.by-space
    /         %h3 5' x 10'
    /       .price
    /         %h3.dark-gray $75.00
    /         %p.price-subtext per month
    /       .price-description
    /         %p
    /           As much as you can fit in a
    /           %br/
    /           5' x 10' area.
    /   .col-md-4.pricing-block
    /     %i.pricing-icon.icon-10x10.by-space
    /     .pricing-info
    /       .pricing-title.by-space
    /         %h3 10' x 10'
    /       .price
    /         %h3.dark-gray $140.00
    /         %p.price-subtext per month
    /       .price-description
    /         %p
    /           As much as you can fit in a
    /           %br/
    /           10' x 10' area.
    /   .col-md-4.pricing-block
    /     %i.pricing-icon.icon-10x20.by-space
    /     .pricing-info
    /       .pricing-title.by-space
    /         %h3 10' x 20'
    /       .price
    /         %h3.dark-gray $250.00
    /         %p.price-subtext per month
    /       .price-description
    /         %p
    /           As much as you can fit in a
    /           %br/
    /           10' x 20' area.





  %section
    %br/
    %br/
    %br/

    .row
      .col-md-12
        .row.homepage-started-row
          .col-md-12
            %h3.dark-gray
              Any Item, Free Pickup,
              %b.blue Storage That Fits
          .col-md-4.col-md-offset-4.col-sm-4.col-sm-offset-4
            .boxed-gray.continue-button.pull-left
              %a.white{"href" => "/signup"}
                %button.btn.btn-primary.blue-bg.yellow-hover Reserve Pickup

  .container
    .row
      .col-md-10.col-md-offset-1
  = render partial: "partials/feedback_tab"
  = render :partial => 'partials/footer'

:javascript
  $(".scroll-to-vid").click(function(){
    $('html, body').animate({scrollTop: $("#signup-action").offset().top - ($(window).height()-50)/2}, 1000);
  });

  $("#scroll-to-about").click(function(){
    $('html, body').animate({scrollTop: $("#what-we-do").offset().top - 100}, 600);
  });

  $("#what-we-do-link").click(function(){
    $('html, body').animate({scrollTop: $("#what-we-do").offset().top - 100}, 800);
  });

  $("#save-much-link").click(function(){
    $('html, body').animate({scrollTop: $("#save-much").offset().top - 100}, 800);
  });

  $("#works-link").click(function(){
    $('html, body').animate({scrollTop: $("#works").offset().top - 100}, 1000);
  });

app/views/static_pages/apartment.html.haml
- content_for :title do
	= "Apartment Landing Page |"
= render partial: 'partials/landing_page', locals: {title: "Apartment Storage Made Easy!", subtitle: "scalable storage picked up and delivered", main_img:"https://s3.amazonaws.com/storage_rails_app_dev/images/homepage_bg_1.png", description: "Quickbox's professional staff will pickup your items right from your home, carefully load them, then transport them to our secure warehouse for safe, reliable storage. Just click \"deliver\" when you want something back and we'll bring it right to you!", extra_classes:""}

app/views/static_pages/boulder.html.haml
- content_for :title do
  = "Boulder |"
= render partial: 'partials/standard_header'

/ # = render :partial => 'partials/signup_bottom_bar'
= javascript_include_tag "new_homepage"
 
/ %p= link_to 'Login', new_user_session_path
#homepage.align-center.landing-page-1
  %h1.no-margin.white.top-bar-title
    Storage Made For Your Budget

  .container

    / = render partial: 'partials/error_messages_object_form', locals: {object: @subscriber}
  // First Page
  %section#introSection.align-center.landing-page.half{ style:"background-image: url('https://s3.amazonaws.com/storage_rails_app_dev/images/homepage_bg_1.png');"}
    .col-md-10.col-md-offset-1.align-center
      %h3.white.no-margin Get 50% Off Your First Month When You Signup Below


    #introSectionContentWrapper
      / %br.hide-on-small 
      .container#main-fold
          
        %br/ 
        %br/ 
        %br/ 
        .main-images.row
          .col-md-7.col-sm-4#fold-img.landing-fold-img
            / %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/TV_Movers_Storate_QuickBox.jpg", :alt => ""}/
            %h1.white Boulder Colorado Storage

          .col-md-4.col-md-offset-1.col-sm-8.align-left.no-padding
            %p.align-left QuickBox On Demand Storage comes directly to you, preforms all the hard work of moving and storing. At a price that can't be beat!
            %br/ 

            // This is the signup box
            .signup-white
              %h3.white#fold-subtitle Signup For Your Storage Disconut
              / %hr.white/ 
              %br/ 
              = form_for Subscriber.new do |f|
                #test123
                  .row
                    .col-md-3.align-right.no-padding
                      / %p.dark-gray Email:
                      %label.dark-gray.hide-on-small{:for => "name"} Name:
                    .col-md-9
                      = f.text_field :name, placeholder: 'Name', class: 'form-control gray-placeholder', required: 'true'
                  %br/ 
                  .row
                    .col-md-3.align-right.no-padding
                      / %p.dark-gray Email:
                      %label.dark-gray.hide-on-small{:for => "email"} Email:

                    .col-md-9
                      = f.email_field :email, placeholder: 'email', class: 'form-control gray-placeholder', required: 'true'
                      %br/ 
                  .boxed-gray.continue-button
                    / %a.white{"href" => "/signup"}
                    %button.btn.btn-primary.blue-bg.blue-bg-hover.no-margin{style: 'font-size: 18px;'}
                      = f.submit "Email My 50% Off Promo"
            / .signup-button
            /   .boxed-gray.continue-button
            /     %button.btn.btn-primary.blue-bg.blue-bg-hover.no-margin{style: 'font-size: 18px;'} Or Sign Up Now!

        %br/ 
        %br/ 
  .blue-bar
    %br/
    %br/
    %br/
    %br/
  %section.container
    .col-md-5.align-left
      %h3.black.little-heavy Local Moving & Storage Help 
      %p QuickBox is Boulder’s local concierge storage company that comes directly to you and takes care of all of the details for moving and storage. We can help you declutter your house, clean out your garage and store your stuff during a move. Our team handles the moving, storage and redelivery of your items at an affordable price in Boulder.
      %h3.black.little-heavy Services We Offer: 
      %ul.bullet-list
        %li Labor for moving items into storage in Boulder
        %li Short term storage in Boulder
        %li Long term storage in Boulder
     

    .col-md-5.col-md-offset-2.align-left
      %h3.black.little-heavy
        %img{class: "benefits-icon", src: "https://s3.amazonaws.com/storage_rails_app_dev/images/license3.png", alt: "Secure facility"}/
        Professional
      %p We’re licensed, bonded and insured so you can rest easy knowing QuickBox will take care of it. Never worry about your stuff again.
      %h3.black.little-heavy
        %img{class: "benefits-icon", src: "https://s3.amazonaws.com/storage_rails_app_dev/images/calendar68.png", alt: "Secure facility"}/
        On Demand
      %p We’re here for you when you need us because time is of the essence. We show up when you need us on your schedule. 
      %h3.black.little-heavy
        %img{class: "benefits-icon", src: "https://s3.amazonaws.com/storage_rails_app_dev/images/padlock27.png", alt: "Secure facility"}/
        Secure
      %p Our facility is secured with state of the art technology, backed by quality insurance & background checked employees. We’ll make sure you’re stuff is safe.  
      


= render :partial => 'partials/footer'

app/views/static_pages/college.html.haml
- content_for :title do
	= "College Student Landing Page |"
= render partial: 'partials/landing_page', locals: {title: "Relax! It's Summertime!", subtitle: "worry-free, door to door storage", main_img:"https://s3.amazonaws.com/storage_rails_app_dev/images/college.jpg", description: "Quickbox's professional staff will pickup your items right from your home, securely load them onto our truck, then transport them to our secure warehouse for safe, reliable storage. Just click \"deliver\" when you want something back and we'll bring it right to you!", extra_classes:"bright-bg"}

app/views/static_pages/cu_student_storage.html.haml
- content_for :title do
	= "Boulder and Denver Student Storage |"
= render partial: 'partials/alt_landingpage', locals: {title: "Student Storage Made Easy", subtitle: "We Pick Up and Deliver Your Items to Storage", main_img:"https://s3.amazonaws.com/storage_rails_app_dev/images/homepage_bg_1.png", description1: "No need to rent a truck or visit a storage unit ever again", description2: "We handle all the moving and storage", description3: "Affordable student pricing specifically for Boulder and Denver area university students", extra_classes:""}

app/views/static_pages/delivery_receipt_email.html.haml
- content_for :title do
  = "Delivery Receipt |"
.row.header-nav
  .nav-links-wrapper.col-md-4
    %a.no-padding.pull-left{href: "/storage_items"}
      %img#menu-img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/qb-logo.png", :alt => ""}/
    %a.pull-left.no-side-padding{href: "/storage_items"}
      %span.light-gray.black-hover#menu-title QuickBox
  .nav-links-wrapper.col-md-1.col-md-offset-4.left-border
    .nav-links
      = link_to "Contact", contact_path, class:"black-hover", target:"_blank"
  .nav-links-wrapper.col-md-1.left-border
    .nav-links
      = link_to "FAQ", contact_path, class:"black-hover", target:"_blank"
  .nav-links-wrapper.col-md-2
    .no-border.nav-links
      = link_to "Visit QuickBox", destroy_user_session_path, method: "delete", class:"black-hover blue"

        





/ SECONDARY HEADER BAR
.container.full-width.blue-bg.no-padding.white.dashboard-header
  .row
    .col-md-12.align-center
      %h1 Your Delivery Receipt
    / Dashboard

%section#about.home-section.text-center
  .heading-about.marginbot-20
    .container
      .row
        .col-lg-8.col-lg-offset-2
          .section-heading
         
            %p
              Hi #{@user.name},
              %br/ 
              %br/ 
              This is your digital receipt to confirm the delivery of #{@delivery_request.storage_items.count} items to #{@delivery_request.user.address_line_1} on #{@pickup_request.delivery_time.strftime("%B %d at %l:%M %p")}.

              %br/ 
              %br/ 

              Please 
              %a.blue{:href => "mailto:team@quickbox.com"} 
                get in touch
              if you have any questions or feedback about how we can improve your experience. We're here to help!
              %br/ 
              %br/ 
              Best,
              %br/ 
              The QuickBox Team
              %br/ 
              %br/ 
              %br/ 
      .row
        .col-md-6.col-md-offset-3.col-sm-6.col-sm-offset-3.col-xs-10.col-xs-offset-1
          %h3.double-underlined Items Delivered 
          .double-line
          .row.inventory
            - @delivery_request.storage_items.each do |delivery_item|
              .col-md-6.col-sm-6.col-xs-6.inventory-entries.no-pointer.delivery-entry{:id => "#{delivery_item.id}"}
                .inner
                  .crop-mask
                    .crop-mask-img-wrapper
                      = image_tag(delivery_item.image_url, class: "img-responsive")                    
                  %h4.storage-item-title= delivery_item.get_title


  / BODY CONTENT: SELECT ITEMS
  .container
    .row
      .col-md-8.col-md-offset-2
        .row
          / End Phone Number &amp; Instructions Box
          .col-md-8.col-md-offset-2.half-opacity.charges-box
            .single-line
            %br/
          .col-md-6.col-md-offset-3.bottom-buttons
            .boxed-gray.continue-button
              %button.btn.btn-primary.blue-bg.blue-bg-hover{:type => "button"}/
              =link_to "Visit The Site", storage_items_path, class:"white"
= render partial: "partials/footer"

app/views/static_pages/denver.html.haml
- content_for :title do
  = "Denver |"
= render partial: 'partials/standard_header'

/ # = render :partial => 'partials/signup_bottom_bar'
= javascript_include_tag "new_homepage"
 
/ %p= link_to 'Login', new_user_session_path
#homepage.align-center.landing-page-1
  %h1.no-margin.white.top-bar-title
    Storage Made For Your Budget

  .container

    / = render partial: 'partials/error_messages_object_form', locals: {object: @subscriber}
  // First Page
  %section#introSection.align-center.landing-page.half{ style:"background-image: url('https://s3.amazonaws.com/storage_rails_app_dev/images/homepage_bg_1.png');"}
    .col-md-10.col-md-offset-1.align-center
      %h3.white.no-margin Get 50% Off Your First Month When You Signup Below


    #introSectionContentWrapper
      / %br.hide-on-small 
      .container#main-fold
          
        %br/ 
        %br/ 
        %br/ 
        .main-images.row
          .col-md-7.col-sm-4#fold-img.landing-fold-img
            / %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/TV_Movers_Storate_QuickBox.jpg", :alt => ""}/
            %h1.white Denver Colorado Storage

          .col-md-4.col-md-offset-1.col-sm-8.align-left.no-padding
            %p.align-left QuickBox On Demand Storage comes directly to you, preforms all the hard work of moving and storing. At a price that can't be beat!
            %br/ 

            // This is the signup box
            .signup-white
              %h3.white#fold-subtitle Signup For Your Storage Disconut
              / %hr.white/ 
              %br/ 
              = form_for Subscriber.new do |f|
                #test123
                  .row
                    .col-md-3.align-right.no-padding
                      / %p.dark-gray Email:
                      %label.dark-gray.hide-on-small{:for => "name"} Name:
                    .col-md-9
                      = f.text_field :name, placeholder: 'Name', class: 'form-control gray-placeholder', required: 'true'
                  %br/ 
                  .row
                    .col-md-3.align-right.no-padding
                      / %p.dark-gray Email:
                      %label.dark-gray.hide-on-small{:for => "email"} Email:

                    .col-md-9
                      = f.email_field :email, placeholder: 'email', class: 'form-control gray-placeholder', required: 'true'
                      %br/ 
                  .boxed-gray.continue-button
                    / %a.white{"href" => "/signup"}
                    %button.btn.btn-primary.blue-bg.blue-bg-hover.no-margin{style: 'font-size: 18px;'}
                      = f.submit "Email My 50% Off Promo"
            / .signup-button
            /   .boxed-gray.continue-button
            /     %button.btn.btn-primary.blue-bg.blue-bg-hover.no-margin{style: 'font-size: 18px;'} Or Sign Up Now!

        %br/ 
        %br/ 
  .blue-bar
    %br/
    %br/
    %br/
    %br/
  %section.container
    .col-md-5.align-left
      %h3.black.little-heavy Local Moving & Storage Help 
      %p QuickBox is a Denver’s local concierge storage company that comes directly to you and takes care of all of the details for moving and storage. We can help you declutter your house, clean out your garage and store your stuff during a move. Our team handles the moving, storage and redelivery of your items at an affordable price in and around Denver 
      %h3.black.little-heavy Services We Offer: 
      %ul.bullet-list
        %li Labor for moving items into storage in Denver
        %li Short term storage in Denver
        %li Long term storage in Denver
     

    .col-md-5.col-md-offset-2.align-left
      %h3.black.little-heavy
        %img{class: "benefits-icon", src: "https://s3.amazonaws.com/storage_rails_app_dev/images/license3.png", alt: "Secure facility"}/
        Professional
      %p We’re licensed, bonded and insured so you can rest easy knowing QuickBox will take care of it. Never worry about your stuff again.
      %h3.black.little-heavy
        %img{class: "benefits-icon", src: "https://s3.amazonaws.com/storage_rails_app_dev/images/calendar68.png", alt: "Secure facility"}/
        On Demand
      %p We’re here for you when you need us because time is of the essence. We show up when you need us on your schedule. 
      %h3.black.little-heavy
        %img{class: "benefits-icon", src: "https://s3.amazonaws.com/storage_rails_app_dev/images/padlock27.png", alt: "Secure facility"}/
        Secure
      %p Our facility is secured with state of the art technology, backed by quality insurance & background checked employees. We’ll make sure you’re stuff is safe.


= render :partial => 'partials/footer'

app/views/static_pages/garage.html.haml
- content_for :title do
	= "Garage Landing Page |"
= render partial: 'partials/landing_page', locals: {title: "Get Your Garage Back.", subtitle: "with scalable storage on demand", main_img:"https://s3.amazonaws.com/storage_rails_app_dev/images/homepage_bg_2.png", description: "Quickbox's professional staff will pickup your items right from your home, securely load them onto our truck, then transport them to our secure warehouse for safe, reliable storage. Just click \"deliver\" when you want something back and we'll bring it right to you!", extra_classes:""}

app/views/static_pages/new-city.html.haml
- content_for :title do
  = "Not In Your City |"
= render partial: 'partials/standard_header'

/ BLUE HEADER BAR
.container.full-width.blue-bg.no-padding.white.dashboard-header.single-row
  .row
    .col-md-12.align-center
      %h1 We're Not In Your City Yet!
    
/ END SECONDARY HEADER


/ Section: ITEM SELECTION
%section#about.home-section.text-center
  .heading-about.marginbot-20
    .container
      .row
        .col-lg-8.col-lg-offset-2
          .section-heading
            = image_tag "https://s3.amazonaws.com/storage_rails_app_dev/images/syn-logo.png", class:"width-30"
            %br/
            %br/
            %br/
            / %h2 We're Not In Your City Yet!
            %p.align-center
              We're trying hard to change the way people do self storage. Right now we're not serving your city, but we hope to be soon. When we do you'll be the first to know! 
              %br/ 
              %br/ 
              In the meantime, please 
              %a{:href => "mailto: team@quickbox.com"} keep in touch!

  %button.btn.btn-primary.gray-bg= link_to "Back To Home", national_path, class:"white"

= render :partial => 'partials/footer'
= render :partial => 'partials/javascriptSource'