config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  devise_scope :user do
    get 'users/sign_out(.:format)', to: 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin_portal', as: 'rails_admin'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :storage_items, only: [:index, :edit, :update]
  resources :delivery_requests, :pickup_requests, only: [:show, :create, :new, :edit, :update, :destroy]
  resources :subscribers, only: [:create]

  get 'admin/block_time', to: 'admin_pages#block_time', as: 'block_time'
  post 'admin/block_time', to: 'admin_pages#create_block_time'
  get 'admin', to: 'admin_pages#admin', as: 'admin'
  get 'admin/record_pickup_request/:id', to: 'admin_pages#record_pickup_request', as: 'admin_record_pickup_request'
  get 'admin/record_delivery_request/:id', to: 'admin_pages#record_delivery_request', as: 'admin_record_delivery_request'
  patch 'admin/record_pickup_request/:id', to: 'admin_pages#save_changes_pickup_request'
  patch 'admin/record_delivery_request/:id', to: 'admin_pages#save_changes_delivery_request'
  get 'admin/assign_driver/:id', to: 'admin_pages#assign_driver', as: 'admin_assign_driver'
  post 'admin/assign_driver/:id', to: 'admin_pages#update_assign_driver'
  patch 'admin/complete_packing_supplies_request/:id', to: 'admin_pages#complete_packing_supplies_request', as: 'complete_packing_supplies_request'
  patch 'admin/complete_pickup_request/:id', to: 'admin_pages#complete_pickup_request', as: 'complete_pickup_request'
  patch 'admin/complete_delivery_request/:id', to: 'admin_pages#complete_delivery_request', as: 'complete_delivery_request'
  get 'admin/sign_in_as_user', to: 'admin_pages#sign_in_as_user', as: 'admin_sign_in_as_user'
  post 'admin/sign_in_as_user' => 'admin_pages#post_sign_in_as_user'

  get '404', to: 'static_pages#not_found', as: 'not_found'
  get '422', to: 'static_pages#server_error'
  get '500', to: 'static_pages#server_error', as: 'server_error'

  get 'new-city' =>'static_pages#new-city'
  get 'national' =>'static_pages#national'
  get 'premium-on-demand-luxury-moving-storage' => 'static_pages#luxury'
  get 'moving-and-storage-on-demand' => 'static_pages#moving_and_storage'
  get 'storage-garage-organization' => 'static_pages#garage_organization'
  get 'cu-student-storage' => 'static_pages#cu_student_storage'
  get 'cheap-storage' => 'static_pages#cheap_storage'
  get 'storage-savings-colorado' => 'static_pages#landing_page_1'
  get 'cu-student-storage-2' => 'static_pages#landing_page_2'
  get 'moving-and-storage-on-demand-denver-boulder' => 'static_pages#landing_page_3'
  get 'premium-on-demand-luxury-moving-storage-2' => 'static_pages#landing_page_4'
  get 'storage-garage-organization-2' => 'static_pages#landing_page_5'
  get 'apartment' => 'static_pages#moving_and_storage'
  get 'student' => 'static_pages#cu_student_storage'

  get 'about', to: 'static_pages#about', as: 'about'
  get 'feedback', to: 'static_pages#feedback', as: 'feedback'
  get 'faq', to: 'static_pages#faq', as: 'faq'
  get 'contact' => 'static_pages#contact'
  get 'email' => 'static_pages#email_example'
  get 'terms-of-service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get 'storage-service-tos', to: 'static_pages#storage_service_tos', as: 'storage_service_tos'
  get 'privacy-policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'users/referral', to: 'users#referral', as: 'users_referral'
  get 'how-quickbox-works', to: 'static_pages#how_quickbox_works', as: 'how_quickbox_works'
  get 'pricing', to: 'static_pages#pricing', as: 'pricing'
  get 'locations/boulder-colorado' => 'static_pages#boulder'
  get 'locations/denver-colorado' => 'static_pages#denver'

  get 'signup', to: 'signup_pages#select_items', as: 'new_signup_pages'
  post 'signup', to: 'signup_pages#post_select_items'
  post 'signup/create_login', to: 'signup_pages#create', as: 'signup_create_login'
  get 'signup/add_payment', to: 'signup_pages#show', as: 'signup_add_payment'
  patch 'signup/add_payment', to: 'signup_pages#add_payment'

  root 'static_pages#homepage'

end

app/views/partials/_admin_header.html.haml
/ / HEADER PARTIAL
/ .container
/   %ul#gn-menu.gn-menu-main.main-header.full-opacity
/     %li.gn-trigger.no-border
/       %a.no-padding{href: "/storage_items"}
/         %img#menu-img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/qb-logo.png", :alt => ""}/
  
/     // ICON & TITLE
/     %li.pull-left.no-border.half-opacity
/       %a.no-side-padding{href: "/storage_items"}
/         %span.light-gray.black-hover#menu-title QuickBox

/     // RIGH SIDE LINKS    
/     %li.pull-right
/       = link_to "Logout", destroy_user_session_path, method: "delete", class:"black-hover"
   
/     / - if mainpage
/     %li.pull-right.no-border
/       %a.light-gray.black-hover{:href => "#delivery-requests"} Deliveries
/     %li.pull-right.no-border
/       %a.light-gray.black-hover{:href => "#supplies-requests"} Supplies
/     %li.pull-right.no-border
/       %a.light-gray.black-hover{:href => "#pickup-requests"} Pickups
/     %li.pull-right.no-border
/       %a.light-gray.black-hover{:href => ""} Top of Page
/     / - else
/     %li.pull-right.no-border
/       = link_to "Admin Main", admin_path, class:"light-gray black-hover"
/       / %a.light-gray.black-hover{:href => ""} Top of Page


.row.header-nav
  .nav-links-wrapper.col-md-5.col-xs-3
    %a.no-padding.pull-left{href: "/"}
      %img#menu-img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/qb-logo.png", :alt => ""}/
    %a.pull-left.no-side-padding.hide-on-small{href: "/"}
      %span.light-gray.black-hover#menu-title QuickBox
  .nav-links-wrapper.col-md-1.left-border.col-xs-3.hide-on-small
    .no-border.nav-links
      %a.light-gray.black-hover{:href => ""} To Top
  .nav-links-wrapper.col-md-2.col-xs-3
    .nav-links
      = link_to "Sign in as user", admin_sign_in_as_user_path, class: 'light-gray black-hover'
  .nav-links-wrapper.col-md-1.col-xs-2.hide-on-small
    .nav-links
      %a.light-gray.black-hover{:href => "#supplies-requests"} Supplies

  .nav-links-wrapper.col-md-1.col-xs-3
    .nav-links
      %a.light-gray.black-hover{:href => "#pickup-requests"} Pickups

  .nav-links-wrapper.col-md-1.col-xs-3
    .nav-links
      %a.light-gray.black-hover{:href => "#delivery-requests"} Deliveries

  .nav-links-wrapper.col-md-1.col-xs-2.hide-on-small
    .nav-links
      = link_to "Logout", destroy_user_session_path, method: "delete", class:"black-hover"

app/views/partials/_admin_request.html.haml
// REQUEST DETAIL VIEW
.row  
  - @pending_pickup_requests.each do |pickup_request|
    .col-md-8.col-md-offset-2.align-left.boxed-grey.fat-white-border
      .request-content.no-margin.row
        .col-md-4
          %h4.blue Pending pickup request
        .col-md-8
          %p
            %span.heavy-font Delivery time requested:
            = pickup_request.delivery_time.strftime("%B %d at %l:%M %p")
          %p.no-margin
            %span.heavy-font  Customer's address:
            = pickup_request.user.address_line_1

      .request-content
      = render partial: "storage_items", locals: {activity: 'pick up', request: pickup_request, show_id: false}

      .row
        .col-md-12
          %br/ 
          = form_for pickup_request, url: complete_pickup_request_path(pickup_request.id) do |f|
            = f.submit 'Mark Complete', class:"pull-right btn btn-skin"
            %a.btn.white.gray-bg.pull-right{:href => "mailto:#{pickup_request.user.email}"}  Email Customer
          %br/
          %br/ 
          %br/  
  %br/

app/views/partials/_delivery_addr_date.html.haml
.boxed-grey.col-md-12
  .row.align-left#validator-id
    .col-md-6
      .form-group.address-form
        %div
          = field.label :address_line_1, "Address:"
          = field.text_field :address_line_1,  autofocus: true, placeholder:"Address Line 1", class:"form-control", id:""
          = field.text_field :address_line_2,  autofocus: true, placeholder:"Address Line 2", class:"form-control", id:""
        .row
          .col-md-6.col-sm-6.col-xs-6.col-lg-6
            = field.text_field :city,  autofocus: true, placeholder:"City", class:"col-md-6 form-control", id:""
          .col-md-3.col-sm-3.col-xs-3.col-lg-3.form-field-wrapper.hide-on-small
            = field.text_field :state,  autofocus: true, class:"form-control", id:"", value: "CO", readonly: true
          .col-md-3.col-sm-3.col-xs-6.col-lg-3.form-field-wrapper
            = field.text_field :zip,  autofocus: true, placeholder:"zip", class:"form-control", id:""
    .col-md-6
      .form-group
        .row
          .col-md-12
            .form-group.delivery-date-group
              = field.label :phone_number, "Phone Number (for delivery)"
              = field.text_field :phone_number,  autofocus: true, placeholder:"(303) 555-1111", class:"form-control", id:""
        .row
          .col-md-12
            .form-group.delivery-date-group
              %label{:for => "name"} Any Special Instructions? (optional)
              = field.text_area :special_instructions, placeholder:"Message", rows:1, class:"form-control"
          %br/
        .row
          .col-md-12
            .form-group.delivery-date-group
              %label{:for => "prefers_calls"} How Do You Prefer to be Contacted?
              %br
              = field.check_box :prefers_calls
              = field.label :prefers_calls, 'Telephone call'
              %br
              = field.check_box :prefers_texts
              = field.label :prefers_texts, 'Text message'
              %br
              = field.check_box :prefers_emails
              = field.label :prefers_emails, 'Email'


:javascript
  $(document).ready(function() {


      $(".form-control").on('input', function() {
        $('#validator-id').data('bootstrapValidator').validate();
      });



      $('#validator-id')
          .bootstrapValidator({
          feedbackIcons: {
          },
          fields: {
            'user[address_line_1]': {
              message: 'The address field is not valid',
              validators: {
                notEmpty: {
                  message: 'The address field can\'t be empty'
                },
                stringLength: {
                  min: 3,
                  message: '*The address must be a real'
                },
              }
            },
            'user[city]': {
              message: 'The city field is not valid',
              validators: {
                notEmpty: {
                  message: '*The city is required'
                },
                stringLength:{
                  min: 2,
                  message: "Valid city is required"
                }
              }
            },
            'user[zip]': {
              message: 'The zip code field is not valid',
              validators: {
                notEmpty: {
                  message: '*zip required'
                },
                between: {
                    min: 80301,
                    max: 80329,
                    message: 'Boulder zip required'
                }
              }
            },
            'user[state]': {
              message: 'The state field is not valid',
              validators: {
                notEmpty: {
                  message: '* state required.'
                },
                stringLength: {
                  min:2,
                  message: "Valid state required"
                }
              }
            },
            'user[phone_number]': {
              message: 'The address field is not valid',
              validators: {
                notEmpty: {
                  message: '*phone number required'
                },

              }
            },
            'user[special_instructions]': {
              message: 'The address field is not valid',
              validators: {}
            }

          }
        })

        // $('#validator-id').data('bootstrapValidator').validate();

    });

app/views/partials/_delivery_date_time.html.haml
= javascript_include_tag "bootstrap-datepicker-parent"

.boxed-grey.col-md-12
  .row#validator-id
    .col-md-6.align-left
      %label{:for => "posted_delivery_date"}
        Date
      #datepicker.input-append.date
        = f.text_field :proposed_date, class:"span2 form-control", id: "datepicker-value", placeholder: 'Which day is best?', value: (f.object.proposed_date.strftime('%m/%d/%Y') unless f.object.proposed_date.blank?)
        %span.add-on
          %i.icon-calendar


    .col-md-6.align-left
      %label{:for => "date-picker"} Time Of Day (let us know what times work for you)
      = f.text_area  :proposed_times
      %br/
      %br/




:javascript
  $(document).ready(function(){
    var start = new Date();
    start.setDate(start.getDate()+1);
    var end = new Date();
    end.setDate(start.getDate()+150);

    $('#datepicker-value').datepicker({
        autoclose: true,
        todayHighlight: true
    });
    $('#datepicker-value').datepicker('setStartDate', start);
    $('#datepicker-value').datepicker('setEndDate', end);
  });

app/views/partials/_error_messages_object_form.html.haml
- if object.errors.any?
  .error_explanation.align-center.col-md-6.col-md-offset-3.light-blue-bg
    %h2= "#{pluralize(object.errors.count, "error")} prohibited this post from being saved:"
    %ul
    - object.errors.full_messages.each do |msg|
      %li
        %p= msg

app/views/partials/_landing_page.html.haml
= render :partial => 'partials/althome_header'
= javascript_include_tag "new_homepage"
 
/ %p= link_to 'Login', new_user_session_path
#homepage.align-center

  // First Page
  %section#introSection.align-center.landing-page{ style:"background-image: url('#{main_img}');"}
    #introSectionContentWrapper
      %br/ 
      %br.hide-on-small 
      %br.hide-on-small
      %br.hide-on-small 
      %br.hide-on-small
      .container#main-fold{class:"#{extra_classes}"}
        .main-images.row
          .col-md-10.col-md-offset-1.align-left
            %h1.white
              = title
           
        .main-images.row
          .col-md-6.col-md-offset-1.col-sm-8.align-left
            %h3.white#fold-subtitle= subtitle
            %br/ 
            %br/ 
            %p.white#fold-description
              = description
            %br/ 
  
            %div#homepage-calltoaction.left
              = link_to new_signup_pages_path, class:"homepage-buttons" do
                %span Get Started
              %a.scroll-to-about.homepage-buttons.outline-button.pointer#more-info{}
                %span.pointer
                  More Info
                  / %span#more-info-blocker .

          .col-md-4.col-md-offset-1.col-sm-4#fold-img.no-padding
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/badge.png", :alt => ""}/

        %br/ 
        %br/ 
    
      .slider-wrapper.hidden
        %ul.bxslider 
          %li 
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/homepage-1.png", :alt => ""}/
          %li 
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/homepage-2.png", :alt => ""}/ 
          %li 
            %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/homepage-3.png", :alt => ""}/ 
        %img{:src => "", :alt => ""}/ 
      %br/ 

  // Divider Blue Bar
  .blue-bar#signup-about.hide-on-small
    .tab.pull-right
      %h5.white.scroll-to-about.pointer
        %i.icon-arrow-down
        Want More Details?
        %i.icon-arrow-down
    %br/ 
    %h2.white QUICKBOX PICKUPS & DELIVERIES
    %br/ 


  // Pickup and Delivery Process Section
  %section.pickup-delivery-process.container
    %br/ 
    %br/ 
    %br/
    %h3.dark-gray.no-margin
      How Do
      %span.blue Free Pickups
      Work?
      
    %hr.half-width.half-opacity
    .container
      %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/pickups-work.png", :alt => ""}/
      %br/ 
      %br/ 
      %br/ 
      %p.center-margin.light-gray.width-60.full-width-small
        You can request a pickup anytime through your personal dashboard. Specify the items you'd like us to pick up, or leave it to our professional drivers to catalog it for you when they arrive.
    %br/   
    %br/ 
    / %br
  .blue-bar#signup-about.hide-on-small.half-opacity
    / %br/ 
    / %h2.white Your Items, A Click Away
    %br/ 
  %br/ 
  %br/ 
  %br/ 
  %br/ 
  %section
    .container.row.pricing-wrapper#items-back
      %h3.no-margin.dark-gray
        How Do I Get
        %span.blue My Items Back?
        
      %hr.width-80.half-opacity
      .col-md-6.pricing-block
        %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/example-interface.png", :alt => ""}/ 
        
      .col-md-6.align-left
        %br/ 
        %br/ 
        / %h4.thin-font All Your Items A Click Away
        / %h4.blue TEST TEST TEST
        %p
          From your QuickBox dashboard you can have any item
          %span.heavy-font delivered to you in as little as a day.
          You can also request new item pickups or packing supplies.
          For deliveries, the pricing is just the monthy cost of the item. 
          %br/ 
          %br/ 
          Need same day delivery, or looking to have regular deliveries? Call about our executive delivery pricing. 
          %br/ 
          %br/ 
          Oh, and
          %span.heavy-font  pickups are always free!


       
    %br/ 
    %br/ 
    %a.header-link{:href => "/faq"}
      %h3.dark-gray 
        Still have questions?
        %span.blue Check out our FAQ!
    %br/ 
    %br/ 
  

  
  // Pricing Section
  .blue-bar#signup-pricing
    %br/ 
    %h2.white What About Pricing?

    %br/ 
  %br/ 
  %br/
  %br/ 
  %section
    / %br/ 
    .container.row.pricing-wrapper
      %h3.dark-gray.no-margin
        %span.blue Flexible Pricing
        By The Item
      %br/ 
      %p.light-gray.width-80 Only have a few items to store? Pricing by the item makes sure you only pay for what you use.
      / %hr.width-80.half-opacity
      .col-md-4.pricing-block
        %i.pricing-icon.icon-icon-box
        .pricing-info
          .pricing-title.by-item
            %h3 Small Items
          .price
            %h3.dark-gray $5.00
            %p.price-subtext per month
          .price-description
            %p Items like boxes (3 cubic feet), tires, bags, or similarly sized objects.
      .col-md-4.pricing-block
        %i.pricing-icon.icon-icon-bike
        .pricing-info
          .pricing-title.by-item
            %h3 Medium Items
          .price
            %h3.dark-gray $12.00
            %p.price-subtext per month
          .price-description
            %p Items like bikes, chairs, skis, luggage, coffee tables, bed-side, tables.
      .col-md-4.pricing-block
        %i.pricing-icon.icon-icon-couch
        .pricing-info
          .pricing-title.by-item
            %h3 Large Items
          .price
            %h3.dark-gray $25.00
            %p.price-subtext per month
          .price-description
            %p Items like couches, mattresses, desks, dressers, chests, bed frames.
    %br/ 
    %br/ 
    %br/



    .container.row.pricing-wrapper
      %h3.dark-gray.no-margin
        %span.dark-blue Traditional Pricing
        By The Space 
      %br/
      %p.light-gray.width-80 Storage by the space is great if you have a lot to store. We still itemize your belongings so you can have individual items delivered, but payment is based on area rather than item count. 
      %br/ 
      / %hr.width-80.half-opacity

      .col-md-4.pricing-block
        %i.pricing-icon.icon-5x10.by-space
        .pricing-info
          .pricing-title.by-space
            %h3 5' x 10'
          .price
            %h3.dark-gray $75.00
            %p.price-subtext per month
          .price-description
            %p
              As much as you can fit in a
              %br/ 
              5' x 10' area.
      .col-md-4.pricing-block
        %i.pricing-icon.icon-10x10.by-space
        .pricing-info
          .pricing-title.by-space
            %h3 10' x 10'
          .price
            %h3.dark-gray $140.00
            %p.price-subtext per month
          .price-description
            %p
              As much as you can fit in a
              %br/ 
              10' x 10' area.
      .col-md-4.pricing-block
        %i.pricing-icon.icon-10x20.by-space
        .pricing-info
          .pricing-title.by-space
            %h3 10' x 20'
          .price
            %h3.dark-gray $250.00
            %p.price-subtext per month
          .price-description
            %p 
              As much as you can fit in a 
              %br/ 
              10' x 20' area.
    %br/ 
    %br/ 
    %p.light-gray.width-80.align-center
      %span.heavy-font 
        Can't decide what's best?
        %span.dark-blue Don't worry!
      %br/ 
      We'll always give you
      the best price
      based on your storage needs.
    .blue-bar.hide-on-small.half-opacity
    %br/ 
    %br/ 
    .container.row.pricing-wrapper
      %h3.dark-gray.no-margin
        Lowest Price
        %span.blue Guarantee!
      %hr.width-80.half-opacity
      %br/ 
      .row
        .col-md-2.col-md-offset-1
          %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/best-price.png", :alt => ""}/ 
        .col-md-8
          %p.align-left
            Already use storage? We offer a  
            %span.heavy-font.blue  minimum of 15% savings
            above your current price gauranteed! Plus, our free pickups make switching easy.
            %br/ 
            %br/ 
            Call us at 720-583-5826 to get started!
      %br/
      %br/ 
      .double-line.half-opacity.width-80.center-margin
    %br/ 
    %br/
  // Pricing Section
  .blue-bar#signup-security
    %br/ 
    %h2.white Your Items Are Always Safe
    %br/ 

  %br/ 
  .container.row.pricing-wrapper.align-center
    %br/ 
    %br/ 
    .width-30.center-margin
      %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/shield_img.png", :alt => ""}/ 

    .col-md-10.col-md-offset-1
      %br/ 
      %p.center-margin QuickBox uses storage facilities with 24-7 video surveylance and sophisticated theft protection to keep your items safe. Further, every item is insured up to $20.00/lb. For those that want even further coverage, we offer premium insurance and climate controlled storage by request. 
  
  %section   
    %br/ 
    %br/ 
    %hr.half-width.half-opacity

    / %br/ 
    %br/ 

    .row
      .col-md-12
        .row.homepage-started-row
          .col-md-12
            %h3.dark-gray
              Any Item, Free Pickup,
              %b.blue Storage That Fits
          .col-md-4.col-md-offset-4.col-sm-4.col-sm-offset-4
            .boxed-gray.continue-button.pull-left
              %a.white{"href" => "/signup"}
                %button.btn.btn-primary.blue-bg.blue-bg-hover Reserve Pickup

  .container
    .row
      .col-md-10.col-md-offset-1
  = render partial: "partials/feedback_tab"
  = render :partial => 'partials/footer'

/ = javascript_include_tag "item_selector"

:javascript
  resizeDiv();


  $(".scroll-to-vid").click(function(){
    $('html, body').animate({scrollTop: $("#signup-action").offset().top - ($(window).height()-50)/2}, 1000);
  });

  $("#scroll-to-about").click(function(){
    $('html, body').animate({scrollTop: $("#what-we-do").offset().top - 100}, 600);
  });

  $("#what-we-do-link").click(function(){
    $('html, body').animate({scrollTop: $("#what-we-do").offset().top - 100}, 800);
  });

  $("#save-much-link").click(function(){
    $('html, body').animate({scrollTop: $("#save-much").offset().top - 100}, 800);
  });

  $("#works-link").click(function(){
    $('html, body').animate({scrollTop: $("#works").offset().top - 100}, 1000);
  });

  $(".scroll-to-about").click(function(){
    $('html, body').animate({scrollTop: $("#signup-about").offset().top - 100}, 600);
  });

  $(document).ready(function(){
    resizeDiv();
  });

app/views/partials/_list_item_4col_field.html.haml
.col-md-3.col-sm-3.col-xs-12.inventory-entries.four-by-entry
  %br/ 
  %img{:alt => "https://s3.amazonaws.com/harnessthecrowd/quickbox/box-default.jpg", :src => "#{imgURL}"}/
  %h4.align-center.pb-10= title
  %p.align-center= price
  %p.align-center.subtitle.no-padding= description
  = form.text_field field_val,  autofocus: true, placeholder:"#{price}", class:"form-control quantity-field", id:"txt-#{id}"
  %button.btn.btn-primary.rounded.full-width.btn-inc{:type => "button", id:"#{id}"} +
  %p.no-opacity.onepxhigh  spacer

app/views/partials/_logged_in_header.html.haml
.row.header-nav
  .nav-links-wrapper.col-lg-7.col-md-6.col-sm-5.col-xs-3
    %a.no-padding.pull-left{href: "/storage_items"}
      %img#menu-img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/qb-logo.png", :alt => ""}/
    %a.pull-left.no-side-padding.invisible-when-tiny{href: "/storage_items"}
      %span#menu-title
        QuickBox
        %span.no-pointer#company-phone (720) 583-5826
  .nav-links-wrapper.col-lg-5.col-md-6.col-sm-7.col-xs-9
    %ul.no-list#header-list
      
      %li.nav-links
        = link_to storage_items_path, class:"black-hover" do
          %i.fa.fa-dashboard
          Dashboard
      %li.nav-links.invisible-at-600
        = link_to [:edit, current_user], class:"black-hover" do
          %i.fa.fa-gear 
          Account
          
      %li.nav-links
        = link_to destroy_user_session_path, method: "delete", class:"black-hover" do
          %i.fa.fa-sign-in 
          Logout
      %li.nav-links#questions-header.invisible-when-small
        = link_to faq_path, class:"black-hover" do
          %i.fa.fa-info-circle

app/views/partials/_quote_gen_modal.html.haml
/ Modal
#quote_gen_popup.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "quote_gen_popupLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4#quote_gen_popupLabel.modal-title.align-center Storage Price Estimator
      .modal-body

        / .col-md-12
        / %h4.pointer.pull-right#quote-close close
        = fields_for @pickup_request, html:{id:"delivery-form"} do |pickup_field|
          = render partial: "partials/storage_items", locals:{f:pickup_field}
          
        / %p hihihi
        / %br/ 
      .modal-footer.no-opacity.huge-left-margin
        %button.btn.btn-default.pull-left{"data-dismiss" => "modal", :type => "button"} Close

app/views/partials/_signup_bottom_bar.html.haml
#bottom-bar
  %a.pointer#close_bottom X 
  = form_for @subscriber do |f|
    .col-md-4.col-md-offset-2.no-side-padding
      %p.pull-right.align-right Get $20 off by entering your email
    .col-md-2
      = f.email_field :email, class: 'form-control', placeholder: 'email'
    .col-md-1.no-side-padding
      = f.submit 'Submit', class: 'btn blue-bg'

:javascript
  $('#close_bottom').click(function(){
    $('#bottom-bar').addClass('hidden');
  });