config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  devise_scope :user do
    get 'users/sign_out(.:format)', to: 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin_portal', as: 'rails_admin'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :storage_items, only: [:index, :edit, :update]
  resources :delivery_requests, :pickup_requests, only: [:show, :create, :new, :edit, :update, :destroy]
  resources :subscribers, only: [:create]

  get 'admin/block_time', to: 'admin_pages#block_time', as: 'block_time'
  post 'admin/block_time', to: 'admin_pages#create_block_time'
  get 'admin', to: 'admin_pages#admin', as: 'admin'
  get 'admin/record_pickup_request/:id', to: 'admin_pages#record_pickup_request', as: 'admin_record_pickup_request'
  get 'admin/record_delivery_request/:id', to: 'admin_pages#record_delivery_request', as: 'admin_record_delivery_request'
  patch 'admin/record_pickup_request/:id', to: 'admin_pages#save_changes_pickup_request'
  patch 'admin/record_delivery_request/:id', to: 'admin_pages#save_changes_delivery_request'
  get 'admin/assign_driver/:id', to: 'admin_pages#assign_driver', as: 'admin_assign_driver'
  post 'admin/assign_driver/:id', to: 'admin_pages#update_assign_driver'
  patch 'admin/complete_packing_supplies_request/:id', to: 'admin_pages#complete_packing_supplies_request', as: 'complete_packing_supplies_request'
  patch 'admin/complete_pickup_request/:id', to: 'admin_pages#complete_pickup_request', as: 'complete_pickup_request'
  patch 'admin/complete_delivery_request/:id', to: 'admin_pages#complete_delivery_request', as: 'complete_delivery_request'
  get 'admin/sign_in_as_user', to: 'admin_pages#sign_in_as_user', as: 'admin_sign_in_as_user'
  post 'admin/sign_in_as_user' => 'admin_pages#post_sign_in_as_user'

  get '404', to: 'static_pages#not_found', as: 'not_found'
  get '422', to: 'static_pages#server_error'
  get '500', to: 'static_pages#server_error', as: 'server_error'

  get 'new-city' =>'static_pages#new-city'
  get 'national' =>'static_pages#national'
  get 'premium-on-demand-luxury-moving-storage' => 'static_pages#luxury'
  get 'moving-and-storage-on-demand' => 'static_pages#moving_and_storage'
  get 'storage-garage-organization' => 'static_pages#garage_organization'
  get 'cu-student-storage' => 'static_pages#cu_student_storage'
  get 'cheap-storage' => 'static_pages#cheap_storage'
  get 'storage-savings-colorado' => 'static_pages#landing_page_1'
  get 'cu-student-storage-2' => 'static_pages#landing_page_2'
  get 'moving-and-storage-on-demand-denver-boulder' => 'static_pages#landing_page_3'
  get 'premium-on-demand-luxury-moving-storage-2' => 'static_pages#landing_page_4'
  get 'storage-garage-organization-2' => 'static_pages#landing_page_5'
  get 'apartment' => 'static_pages#moving_and_storage'
  get 'student' => 'static_pages#cu_student_storage'

  get 'about', to: 'static_pages#about', as: 'about'
  get 'feedback', to: 'static_pages#feedback', as: 'feedback'
  get 'faq', to: 'static_pages#faq', as: 'faq'
  get 'contact' => 'static_pages#contact'
  get 'email' => 'static_pages#email_example'
  get 'terms-of-service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get 'storage-service-tos', to: 'static_pages#storage_service_tos', as: 'storage_service_tos'
  get 'privacy-policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'users/referral', to: 'users#referral', as: 'users_referral'
  get 'how-quickbox-works', to: 'static_pages#how_quickbox_works', as: 'how_quickbox_works'
  get 'pricing', to: 'static_pages#pricing', as: 'pricing'
  get 'locations/boulder-colorado' => 'static_pages#boulder'
  get 'locations/denver-colorado' => 'static_pages#denver'

  get 'signup', to: 'signup_pages#select_items', as: 'new_signup_pages'
  post 'signup', to: 'signup_pages#post_select_items'
  post 'signup/create_login', to: 'signup_pages#create', as: 'signup_create_login'
  get 'signup/add_payment', to: 'signup_pages#show', as: 'signup_add_payment'
  patch 'signup/add_payment', to: 'signup_pages#add_payment'

  root 'static_pages#homepage'

end

app/controllers/admin_pages_controller.rb
class AdminPagesController < ApplicationController
	include ParamExtraction

	before_action :authenticate_admin!

	def post_sign_in_as_user
		@user = User.where(sign_in_as_user_params(params)).first
		redirect_to admin_sign_in_as_user_url, alert: 'User does not exist.' and return unless @user
		sign_in @user
		redirect_to storage_items_url and return
	end

	def sign_in_as_user
		@user = User.new
	end

	def admin
		@user = current_user
		@pending_pickup_requests = PickupRequest.where(completion_time: nil).order(:delivery_time)
		@pending_pickup_requests_assigned = PickupRequest.where(completion_time: nil).where.not(driver_name: nil).order(:delivery_time)
		@pending_pickup_requests_unassigned = PickupRequest.where(completion_time: nil, driver_name: nil).order(:delivery_time)

		@pending_delivery_requests = DeliveryRequest.where(completion_time: nil).order(:delivery_time)
		@pending_delivery_requests_assigned = DeliveryRequest.where(completion_time: nil).where.not(driver_name: nil).order(:delivery_time)
		@pending_delivery_requests_unassigned = DeliveryRequest.where(completion_time: nil, driver_name: nil).order(:delivery_time)

		@pending_packing_supplies_requests = PackingSuppliesRequest.where(completion_time: nil).order(:delivery_time)
	end

	def assign_driver
		@request = Request.find(params[:id])
	end

	def update_assign_driver
		@request = Request.find(params[:id])
		@request.skip_delivery_validation = true
		@request.update(params.require(:request).permit(:driver_name, :driver_notes))
		redirect_to :admin, notice: 'Driver has been assigned to the request.' and return
	end

	def record_pickup_request
		@pickup_request = PickupRequest.find(params[:id])
	end

	def record_delivery_request
		@delivery_request = DeliveryRequest.find(params[:id])
	end

	def save_changes_pickup_request
		@pickup_request = PickupRequest.find(params[:id])
		@pickup_request.skip_delivery_validation = true
		@pickup_request.update(complete_pickup_request_params(params))
		if @pickup_request.valid?
			redirect_to({action: :record_pickup_request}, notice: 'Changes saved') and return
		else
			flash.now[:alert] = 'There were some errors that prevented saving'
			render action: :record_pickup_request and return
		end
	end

	def save_changes_delivery_request
		@delivery_request = DeliveryRequest.find(params[:id])
		@delivery_request.skip_delivery_validation = true
		@delivery_request.update(complete_delivery_request_params(params))
		if @delivery_request.valid?
			redirect_to({action: :record_delivery_request}, notice: 'Changes saved') and return
		else
			flash.now[:alert] = 'There were some errors that prevented saving.'
			render action: :record_delivery_request and return
		end
	end

	def complete_packing_supplies_request
		packing_supplies_request = PackingSuppliesRequest.find(params[:id])
		Stripe::Charge.create(amount: (packing_supplies_request.price * 100).to_i, currency: 'usd', customer: packing_supplies_request.user.stripe_customer_identifier, description: "Packing supplies shipped on #{Time.zone.now.strftime('%m/%d')}", statement_description: "PACKING SUPPLIE")
		packing_supplies_request.update(completion_time: Time.zone.now, driver_id: current_user.id)
		redirect_to :admin, notice: 'Packing supplies request marked shipped' and return
	end

	def complete_pickup_request
		@pickup_request = PickupRequest.find(params[:id])
		error = @pickup_request.complete(current_user)
		if error
			flash.now[:alert] = error
			render :record_pickup_request and return
		end
		redirect_to :admin, notice: 'Pickup request marked complete.' and return
	end

	def complete_delivery_request
		@delivery_request = DeliveryRequest.find(params[:id])
		error = @delivery_request.complete(current_user)
		if error
			flash.now[:alert] = error
			render :record_delivery_request and return
		end
		redirect_to :admin, notice: 'Delivery request marked complete' and return
	end

	def create_block_time
		ut = UnavailableTime.create(params.require(:unavailable_time).permit(:unavailable_date, :start_hour, :end_hour))
		if ut.valid?
			redirect_to :admin, notice: 'Time blocked out successfully' and return
		else
			redirect_to :admin, alert: 'There was an error with blocking out that time.' and return
		end
	end

	def block_time

	end

	private

	def authenticate_admin!
		if not (current_user and current_user.admin)
			redirect_to not_found_path and return
		end
	end

end

app/views/admin_pages/_admin_delivery_request_info.html.haml
.col-md-8.col-md-offset-2.align-left.boxed-grey.fat-white-border.request-entry
  .request-content.no-margin
    

    .col-md-4
      %i.icon-delivery.fa.pull-left 
      %h3.blue.heavy-font Pend Delivery
    .col-md-2.pull-left
      = link_to admin_assign_driver_path(id: delivery_request.id), class: "pointer white details-btn" do
        %h1.btn.btn-default.red Assign
        %br.show-on-small
    .col-md-3.pull-left.col-xs
      %a.pointer.white.details-btn{:id => "#{delivery_request.id}"}
        %h1.btn.btn-default.gray-bg View Details
        %br.show-on-small
    .col-md-3.pull-left.no-padding
      = link_to "Record & Complete", admin_record_delivery_request_path(id: delivery_request.id), class: "btn btn-skin white"
      


      / .col-md-3.pull-left
      /   %a.pointer.white.details-btn{:id => "#{delivery_request.id}"} 
      /     %h1.btn.btn-default.gray-bg View Details
      / .col-md-3.pull-left
      /   = link_to "Record & Complete", admin_record_delivery_request_path(id: delivery_request.id), class: "btn btn-skin white"
      / %a.btn.btn-skin.white{:href => ""} Record & Complete 
  .row
    
  .request-content
    .storage-items
      .row.storage-item
        = render partial: "partials/admin_driver_details", locals:{request:delivery_request}
        .col-md-4
          %p
            %ul.no-list
              %li.heavy-font 
                %span Boxes:
                %span.pull-right ID

              - delivery_request.storage_items.where(item_type: 'small').each do |small_item|
                %li.delivery-detail
                  small_item.title
                  %span.pull-right #{small_item.user_item_number}
              %li.heavy-font
                %span Medium Items:
                %span.pull-right ID
              - delivery_request.storage_items.where(item_type: 'medium').each do |medium_item|
                %li.delivery-detail 
                  medium_item.title
                  %span.pull-right #{medium_item.user_item_number}

              %li.heavy-font
                %span Large Items: 
                %span.pull-right ID
              - delivery_request.storage_items.where(item_type: 'large').each do |large_item|
                %li.delivery-detail 
                  large_item.title
                  %span.pull-right #{large_item.user_item_number}

              %li.heavy-font
                %span XL Items
                %span.pull-right ID
              - delivery_request.storage_items.where(item_type: 'extra_large').each do |extra_large_item|
                %li.delivery-detail
                  = extra_large_item.title
                  %span.pull-right #{extra_large_item.user_item_number}
  / .request-content
  .admin-details.hidden{:id => "#{delivery_request.id}-details"}
    = render partial: "storage_items", locals: {activity: 'deliver', request: delivery_request, show_id: true}
  %p.no-opacity a

app/views/admin_pages/_admin_pickup_request_info.html.haml
.col-md-8.col-md-offset-2.align-left.boxed-grey.fat-white-border
  .request-content.no-margin.row
    - if assigned
      .col-md-3
        %i.icon-pickup.fa.pull-left 
        %h3.blue.heavy-font Pickup
    - else
      .col-md-3.red-font
        %i.icon-pickup.fa.pull-left 
        %h3.heavy-font Pending Pickup    
    .col-md-2.pull-left
      = link_to admin_assign_driver_path(id: pickup_request.id), class: "pointer white details-btn" do
        %h1.btn.btn-default.red Assign
    .col-md-3.pull-left
      %a.pointer.white.details-btn{:id => "#{pickup_request.id}"}
        %h1.btn.btn-default.gray-bg View Details
    .col-md-3.pull-left
      = link_to "Record & Complete", admin_record_pickup_request_path(id: pickup_request.id), class: "btn btn-skin white"
  .request-content
    .storage-items
      .row.storage-item
        = render partial: "partials/admin_driver_details", locals:{request:pickup_request}
        .col-md-4
          %p
            %span Items Requested
            %ul.no-list
              %li
                Boxes:
                %span.pull-right= pickup_request.storage_items.where(item_type: 'small').count

              %li
                Medium Items:
                %span.pull-right= pickup_request.storage_items.where(item_type: 'medium').count
              %li
                Large Items:
                %span.pull-right= pickup_request.storage_items.where(item_type: 'large').count
              %li
                XL Items:
                %span.pull-right= pickup_request.storage_items.where(item_type: 'extra_large').count
    .admin-details.hidden{:id => "#{pickup_request.id}-details"}
      = render partial: "partials/admin_pickup_detail", locals: {pickup_request: pickup_request}
    %p.no-opacity a

app/views/admin_pages/assign_driver.html.haml
= render partial: "partials/admin_record_header"


.container.full-width.blue-bg.no-padding.white.dashboard-header
  
  .row
    .col-md-12.col-xs-12.align-center
      .single-line.no-opacity
      %h1.no-side-margin ADMIN PAGE


.container#admin-page
  ////////////////////////////////////////////////////////////////////////////////////////////////
  //////////// PICKUP REQUESTS ///////////////////////////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////////////////////////////////////
  %section.text-center#pickup-requests
    .heading-about.marginbot-20
      .container
        .row
          .col-lg-8.col-lg-offset-2
            .section-heading
              %h2.no-margin Pending Pickup Requests
    .container.request-entry
      // For Each Pickup Request

      = form_for :request, {url: admin_assign_driver_path(@request.id)} do |f|
        .row  
          .col-md-8.col-md-offset-2.align-left.boxed-grey.fat-white-border
            .request-content.row
              .col-md-5
                %h3.blue.heavy-font Pending Pickup
              .col-md-4.col-md-offset-3.pull-right.align-right
                = link_to "Back To Dashboard", admin_path, class: "btn btn-skin gray-bg white"
            .request-content
              .storage-items
                .row.storage-item
                  .div
                    = render partial: "partials/admin_driver_details", locals:{request:@request}
                    .col-md-4
                      %p
                        %span Items Requested
                        %ul.no-list
                          %li
                            Boxes:
                            %span.pull-right= @request.storage_items.where(item_type: 'small').count

                          %li
                            Medium Items:
                            %span.pull-right= @request.storage_items.where(item_type: 'medium').count
                          %li
                            Large Items:
                            %span.pull-right= @request.storage_items.where(item_type: 'large').count
                          %li
                            XL Items:
                            %span.pull-right= @request.storage_items.where(item_type: 'extra_large').count
                  / %p.onepxhigh test
                  %br/ 
                  %br/ 
                  .single-line
                    %p.no-opacity invisible
                  .row
                    .col-md-6
                      = f.label :driver_name, "Picked Up By:"
                      = f.text_field :driver_name,  autofocus: true, placeholder:"Driver Name", class:"col-md-6 form-control", id:""
                    .col-md-6
                      = f.label :driver_notes, "Notes:"
                      = f.text_field :driver_notes,  autofocus: true, placeholder:"Notes", class:"col-md-6 form-control", id:""
             
       
            %br/ 
            .row
              .col-md-12.align-center
                = f.submit "Assign Driver", class: "btn btn-skin white pull-right"
                = link_to admin_path, class: "pointer white pull-left details-btn" do
                  %h1.btn.btn-default.gray-bg Back
            .row
              %p.no-opacity ps
          %br/

  
  %br/ 
  .single-line
  .single-line






= render partial: "partials/footer"

:javascript
  $(".details-btn").click(function(){
    var id = $(this).attr("id");
    var details = $("#" + id + "-details");
    console.log(id+"-details");
    if ($(details).hasClass("hidden")) {
      $("#" + id + " h1").html("Hide Details");
      $(details).removeClass("hidden");
    }
    else {
      $("#" + id + " h1").html("View Details");
      $(details).addClass("hidden");
    }
  });

// admin/record_pickup_request/id

app/views/admin_pages/block_time.html.haml
= render partial: "partials/admin_record_header"


.container.full-width.blue-bg.no-padding.white.dashboard-header
  
  .row
    .col-md-12.col-xs-12.align-center
      .single-line.no-opacity
      %h1.no-side-margin ADMIN PAGE


.container#admin-page
  ////////////////////////////////////////////////////////////////////////////////////////////////
  //////////// PICKUP REQUESTS ///////////////////////////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////////////////////////////////////
  %section.text-center#pickup-requests
    .heading-about.marginbot-20
      .container
        .row
          .col-lg-8.col-lg-offset-2
            .section-heading
              %h2.no-margin Block Time
    .container.request-entry
      // For Each Pickup Request

      = form_for :unavailable_time, url: admin_block_time_path do |f|
        .row  
          .boxed-grey.col-md-8.col-md-offset-2
            .row#validator-id
              .col-md-4.align-left
                %label{:for => "posted_delivery_date"} Delivery Date <span class="required_label">  * required </span>
                
                #datepicker.input-append.date
                  =f.text_field :unavailable_date, class:"span2 form-control", id: "datepicker-value", placeholder: 'Which day is best?'
                  %span.add-on
                    %i.icon-calendar
               
              .col-md-4.align-left
                %label{:for => "date-picker"} Start Time
                = f.select  :start_hour, options_for_select([["Choose a time"]]),{}, {class:"form-control selectpicker", id:"start_block"}
                %br/ 
              .col-md-4.align-left
                %label{:for => "date-picker"} End Time
                = f.select  :end_hour, options_for_select([["Choose a time"]]),{}, {class:"form-control selectpicker", id:"end_block"}
                %br/ 
            .row
              .col-md-12.align-center
                = f.submit "Block Off Time", class: "btn btn-skin white pull-right"
                = link_to admin_path, class: "pointer white pull-left details-btn" do
                  %h1.btn.btn-default.gray-bg Back To Dashboard
                %br/
                %br/ 
         
          %br/ 
          %br/ 

        %br/ 
        %br/ 
        %br/ 
        %br/ 
        %br/ 
        %br/ 
        %br/ 
        %br/ 
        %br/
  
  // System for un-blocking time
  / %section.text-center#pickup-requests
  /   .heading-about.marginbot-20
  /     .container
  /       .row
  /         .col-lg-8.col-lg-offset-2
  /           .section-heading
  /             %h2.no-margin Un-Block Time
  /   .container.request-entry
  /     // For Each Pickup Request

  /     = form_for :request, {url: admin_assign_driver_path(@request.id)} do |f|
  /       .row  
  /         .boxed-grey.col-md-8.col-md-offset-2
  /           .row#validator-id
  /             .col-md-4.align-left
  /               %label{:for => "posted_delivery_date"} Delivery Date <span class="required_label">  * required </span>
                
  /               #datepicker.input-append.date
  /                 =f.text_field :posted_delivery_date, class:"span2 form-control", id: "datepicker-value", placeholder: 'Which day is best?'
  /                 %span.add-on
  /                   %i.icon-calendar
               
  /             .col-md-4.align-left
  /               %label{:for => "date-picker"} Time Of Day
  /               = f.select  :posted_delivery_time, options_for_select([["Choose a time"]]),{}, {class:"form-control selectpicker", id:"#start_block"}
  /               %br/ 
  /             .col-md-4.align-left
  /               %label{:for => "date-picker"} Time Of Day
  /               = f.select  :posted_delivery_time, options_for_select([["Choose a time"]]),{}, {class:"form-control selectpicker", id:"#end_block"}
  /               %br/ 
  /           .row
  /             .col-md-12.align-center
  /               = f.submit "Block Off Time", class: "btn btn-skin white pull-right"
  /               = link_to admin_path, class: "pointer white pull-left details-btn" do
  /                 %h1.btn.btn-default.gray-bg Back
  /               %p.no-opacity hidden-spacer
  /               %br/ 
         
  /         %br/ 
  /         %br/ 


  
  






= render partial: "partials/footer"

:javascript
  $('#datepicker').datepicker({
      daysOfWeekDisabled: "0",
      autoclose: true,
      todayHighlight: true
  });

  var start = new Date();
  var end = new Date();
  end.setDate(start.getDate()+30);
  $('#datepicker').datepicker('setStartDate', start);
  $('#datepicker').datepicker('setEndDate', end);


  $('#datepicker').on('changeDate', function(){
    var available_delivery_times = #{Request.available_delivery_times.to_json};
    console.log(available_delivery_times);
    updateDropdownDates('#datepicker-value', "#end_block", available_delivery_times);
    updateDropdownDates('#datepicker-value', "#start_block", available_delivery_times);
  });


// admin/record_pickup_request/id

app/views/admin_pages/record_delivery_request.html.haml
= render partial: "partials/admin_record_header"
= javascript_include_tag  "admin_record"


.container.full-width.blue-bg.no-padding.white.dashboard-header
  
  .row
    .col-md-12.col-xs-12.align-center
      .single-line.no-opacity
      %h1.no-side-margin ADMIN PAGE


.container#admin-page
  ////////////////////////////////////////////////////////////////////////////////////////////////
  //////////// PICKUP REQUESTS ///////////////////////////////////////////////////////////////////
  ////////////////////////////////////////////////////////////////////////////////////////////////
  %section.text-center#pickup-requests
    .heading-about.marginbot-20
      .container
        .row
          .col-lg-8.col-lg-offset-2
            .section-heading
              %h2.no-margin Pending Delivery Requests
    .container
      = render partial: 'partials/error_messages_object_form', locals: {object: @delivery_request}
    .container.request-entry
      = form_for @delivery_request, url: admin_record_delivery_request_path(@delivery_request.id), method: :patch  do |field|  
        .row  
          .col-md-8.col-md-offset-2.align-left.boxed-grey.fat-white-border
            .request-content.row
              .col-md-5
                %h3.blue.heavy-font Pending Delivery
              .col-md-4.col-md-offset-3.pull-right.align-right
                = link_to "Back To Dashboard", admin_path, class: "btn btn-skin gray-bg white"
            .request-content
              .storage-items
                .row.storage-item
                  .div
                    = render partial: "partials/admin_driver_details", locals:{request:@delivery_request}
                    .col-md-4
                      %p
                        %span Items Requested
                        %ul.no-list
                          %li
                            Boxes:
                            %span.pull-right= @delivery_request.storage_items.where(item_type: 'small').count

                          %li
                            Medium Items:
                            %span.pull-right= @delivery_request.storage_items.where(item_type: 'medium').count
                          %li
                            Large Items:
                            %span.pull-right= @delivery_request.storage_items.where(item_type: 'large').count
                          %li
                            XL Items:
                            %span.pull-right= @delivery_request.storage_items.where(item_type: 'extra_large').count
                  / %p.onepxhigh test
                  %br/ 
                  %br/ 
                  .single-line
                    %p.no-opacity invisible
                  .row
                    .col-md-6
                      = field.label "Delivered By:"
                      = field.text_field :driver_name,  autofocus: true, placeholder:"Driver Name", class:"col-md-6 form-control", id:""
                    .col-md-6
                      = field.label "Notes:"
                      = field.text_field :driver_notes,  autofocus: true, placeholder:"Notes", class:"col-md-6 form-control", id:""
              .admin-details{:id => "#{@delivery_request.id}-details"}
                = render partial: "partials/admin_delivery_form", locals: {delivery_request: @delivery_request, form: field}
            .row.no-margin
              %br/ 
              %br/ 
              .col-md-4.align-left
                = link_to admin_path, class: "pointer white details-btn", id: "#{@delivery_request.id}" do
                  %h1.btn.btn-default.gray-bg Back
              .col-md-4.pull-right.align-center
                = link_to "Record & Complete", complete_delivery_request_path(@delivery_request.id), class: "btn btn-skin white", id:"record-complete", method: :patch
              .col-md-4.pull-right.align-center
                = field.submit "Save Changes", class: "btn btn-skin white red "
            .row.align-center
              %br/
              %br/ 
              %p Remember you have to save your changes before completing a request
            .row
              %p.no-opacity ps
          %br/

  
  %br/ 
  .single-line
  .single-line






= render partial: "partials/footer"

app/views/admin_pages/record_pickup_request.html.haml
= javascript_include_tag  "admin_record"
#admin-page
  = render partial: "partials/admin_record_header"


  .container.full-width.blue-bg.no-padding.white.dashboard-header
    .col-md-12.col-xs-12.align-center
      .single-line.no-opacity
      %h1.no-side-margin ADMIN PAGE



  .container
    ////////////////////////////////////////////////////////////////////////////////////////////////
    //////////// PICKUP REQUESTS ///////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////////////////////////
    %section.text-center#pickup-requests
      .heading-about.marginbot-20
        .container
          .row
            .col-lg-8.col-lg-offset-2
              .section-heading
                %h2.no-margin Pending Pickup Requests
      .container
        = render partial: 'partials/error_messages_object_form', locals: {object: @pickup_request}
      .container.request-entry
        // For Each Pickup Request
        = form_for @pickup_request, url: admin_record_pickup_request_path(@pickup_request.id), method: :patch  do |field|  
          .row  
            .col-md-8.col-md-offset-2.align-left.boxed-grey.fat-white-border
              .request-content.row.align-center
                .col-md-5.col-xs-12
                  %h3.blue.heavy-font Pending Pickup
                .col-md-4.col-md-offset-3.pull-right.col-xs-12
                  = link_to "Back To Dashboard", admin_path, class: "btn btn-skin gray-bg white"
              .request-content
                .storage-items
                  .row.storage-item
                    .div
                      = render partial: "partials/admin_driver_details", locals:{request:@pickup_request}
                      .col-md-4
                        %p
                          %span Items Requested
                          %ul.no-list
                            %li
                              Boxes:
                              %span.pull-right= @pickup_request.storage_items.where(item_type: 'small').count

                            %li
                              Medium Items:
                              %span.pull-right= @pickup_request.storage_items.where(item_type: 'medium').count
                            %li
                              Large Items:
                              %span.pull-right= @pickup_request.storage_items.where(item_type: 'large').count
                            %li
                              XL Items:
                              %span.pull-right= @pickup_request.storage_items.where(item_type: 'extra_large').count
                    %br/ 
                    %br/ 
                    
                    .row
                      .col-md-6
                        = field.label :driver_name, "Picked Up By:"
                        = field.text_field :driver_name,  autofocus: true, placeholder:"Driver Name", class:"col-md-6 form-control", id:""
                      .col-md-6
                        = field.label :driver_notes, "Notes:"
                        = field.text_field :driver_notes,  autofocus: true, placeholder:"Notes", class:"col-md-6 form-control", id:""
                    .row
                      %br/ 
                      .col-md-6
                        = field.label :one_time_payment, "One Time Payment (if applicable)", class:"half-opacity"
                        = field.text_field :one_time_payment,  autofocus: true, class:"col-md-6 form-control", id:""
                      .col-md-6

                .admin-details{:id => "#{@pickup_request.id}-details"}
                  = render partial: "partials/admin_pickup_form", locals: {pickup_request: @pickup_request, form: field}
                = link_to_add_fields "Add Item", field, :storage_items, @pickup_request
                %br/ 
                %p.no-opacity ps
              %br/ 
              .row
                .col-md-4.align-center.col-xs-12
                  %br/ 
                  = link_to admin_path, class: "pointer white details-btn", id: "#{@pickup_request.id}" do
                    %h1.btn.btn-default.gray-bg Back

                .col-md-4.pull-right.align-center.col-xs-12
                  %br/ 
                  = link_to "Record & Complete", complete_pickup_request_path(@pickup_request.id), class: "btn btn-skin white", id:"record-complete", method: :patch
                .col-md-4.pull-right.align-center.col-xs-12
                  %br/ 
                  = field.submit "Save Changes", class: "btn btn-skin white red"
              .row.align-center
                %br/
                %br/ 
                %p Remember you have to save your changes before completing a request
               
              .row

                %p.no-opacity ps
            %br/

    
    %br/ 
    .single-line
    .single-line






  = render partial: "partials/footer"