config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:edit, :update]
  devise_scope :user do
    get 'users/sign_out(.:format)', to: 'devise/sessions#destroy'
  end

  mount RailsAdmin::Engine => '/admin_portal', as: 'rails_admin'
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  resources :storage_items, only: [:index, :edit, :update]
  resources :delivery_requests, :pickup_requests, only: [:show, :create, :new, :edit, :update, :destroy]
  resources :subscribers, only: [:create]

  get 'admin/block_time', to: 'admin_pages#block_time', as: 'block_time'
  post 'admin/block_time', to: 'admin_pages#create_block_time'
  get 'admin', to: 'admin_pages#admin', as: 'admin'
  get 'admin/record_pickup_request/:id', to: 'admin_pages#record_pickup_request', as: 'admin_record_pickup_request'
  get 'admin/record_delivery_request/:id', to: 'admin_pages#record_delivery_request', as: 'admin_record_delivery_request'
  patch 'admin/record_pickup_request/:id', to: 'admin_pages#save_changes_pickup_request'
  patch 'admin/record_delivery_request/:id', to: 'admin_pages#save_changes_delivery_request'
  get 'admin/assign_driver/:id', to: 'admin_pages#assign_driver', as: 'admin_assign_driver'
  post 'admin/assign_driver/:id', to: 'admin_pages#update_assign_driver'
  patch 'admin/complete_packing_supplies_request/:id', to: 'admin_pages#complete_packing_supplies_request', as: 'complete_packing_supplies_request'
  patch 'admin/complete_pickup_request/:id', to: 'admin_pages#complete_pickup_request', as: 'complete_pickup_request'
  patch 'admin/complete_delivery_request/:id', to: 'admin_pages#complete_delivery_request', as: 'complete_delivery_request'
  get 'admin/sign_in_as_user', to: 'admin_pages#sign_in_as_user', as: 'admin_sign_in_as_user'
  post 'admin/sign_in_as_user' => 'admin_pages#post_sign_in_as_user'

  get '404', to: 'static_pages#not_found', as: 'not_found'
  get '422', to: 'static_pages#server_error'
  get '500', to: 'static_pages#server_error', as: 'server_error'

  get 'new-city' =>'static_pages#new-city'
  get 'national' =>'static_pages#national'
  get 'premium-on-demand-luxury-moving-storage' => 'static_pages#luxury'
  get 'moving-and-storage-on-demand' => 'static_pages#moving_and_storage'
  get 'storage-garage-organization' => 'static_pages#garage_organization'
  get 'cu-student-storage' => 'static_pages#cu_student_storage'
  get 'cheap-storage' => 'static_pages#cheap_storage'
  get 'storage-savings-colorado' => 'static_pages#landing_page_1'
  get 'cu-student-storage-2' => 'static_pages#landing_page_2'
  get 'moving-and-storage-on-demand-denver-boulder' => 'static_pages#landing_page_3'
  get 'premium-on-demand-luxury-moving-storage-2' => 'static_pages#landing_page_4'
  get 'storage-garage-organization-2' => 'static_pages#landing_page_5'
  get 'apartment' => 'static_pages#moving_and_storage'
  get 'student' => 'static_pages#cu_student_storage'

  get 'about', to: 'static_pages#about', as: 'about'
  get 'feedback', to: 'static_pages#feedback', as: 'feedback'
  get 'faq', to: 'static_pages#faq', as: 'faq'
  get 'contact' => 'static_pages#contact'
  get 'email' => 'static_pages#email_example'
  get 'terms-of-service', to: 'static_pages#terms_of_service', as: 'terms_of_service'
  get 'storage-service-tos', to: 'static_pages#storage_service_tos', as: 'storage_service_tos'
  get 'privacy-policy', to: 'static_pages#privacy_policy', as: 'privacy_policy'
  get 'users/referral', to: 'users#referral', as: 'users_referral'
  get 'how-quickbox-works', to: 'static_pages#how_quickbox_works', as: 'how_quickbox_works'
  get 'pricing', to: 'static_pages#pricing', as: 'pricing'
  get 'locations/boulder-colorado' => 'static_pages#boulder'
  get 'locations/denver-colorado' => 'static_pages#denver'

  get 'signup', to: 'signup_pages#select_items', as: 'new_signup_pages'
  post 'signup', to: 'signup_pages#post_select_items'
  post 'signup/create_login', to: 'signup_pages#create', as: 'signup_create_login'
  get 'signup/add_payment', to: 'signup_pages#show', as: 'signup_add_payment'
  patch 'signup/add_payment', to: 'signup_pages#add_payment'

  root 'static_pages#homepage'

end

app/models/storage_item.rb
class StorageItem < ActiveRecord::Base
	@item_not_delivered = false

	def self.always_discount
		0.15
	end

	def self.item_types
		{'small' => 7.0, 'medium' => 15.0, 'large' => 30.0, 'extra_large' => 50.0}
	end

	def self.volume_discounts
		[
			[10, 0.0],
			[85, 0.0],
			[100, 0.1],
			[180, 0.15],
			[225, 0.20],
			[350, 0.25],
			[500 , 0.3]
		]
	end

	def self.duration_discounts
		[
			[3, 0.0],
			[6, 0.00],
			[10, 0.10],
			[13, 0.15],
			[19, 0.2],
			[25, 0.25],
			[1000000, 0.3]
		]
	end

	def self.calculate_duration_discount(duration)
		self.duration_discounts.each do |discount_group|
			return discount_group[1] if duration < discount_group[0]
		end
	end

	def self.calculate_volume_discount(base_price)
		self.volume_discounts.each do |discount_group|
		  return discount_group[1] if base_price < discount_group[0]
		end
	end

	has_attached_file :image
	has_paper_trail
	belongs_to :user
	belongs_to :driver, class_name: 'User'
	belongs_to :delivery_request
	belongs_to :pickup_request

	before_create :add_user_item_number

	validates :user_id, :item_type, :pickup_request_id, presence: true
	validates :item_type, inclusion: { in: self.item_types.keys.map { |item| item.to_s }, message: 'must be a real type.' }
	validates_attachment :image, size: { less_than: 10.megabytes }, content_type: { content_type: /\Aimage\/.*\Z/ }
	validate :if_entered_storage_then_must_have_title_and_image

	before_save :remove_delivery_request_if_item_not_delivered

	def item_not_delivered=(item_not_delivered)
		attribute_will_change!(:item_not_delivered)
		@item_not_delivered = if item_not_delivered and item_not_delivered.to_i == 1 then true else false end
	end

	def item_not_delivered
		if @item_not_delivered then @item_not_delivered else false end
	end

	def price
		StorageItem.item_types[self.item_type]
	end

	def discounted_price
		discount = self.discount.to_f
		if discount and discount > 0
			self.price*((100.0 - discount) / 100.0)
		else
			self.price
		end
	end

	def correct_low_duration_discount(new_discount, old_discount, months)
		discount_diff = new_discount - old_discount
		amount_to_credit = self.discounted_price * months * discount_diff * 100.0 * -1.0

		Stripe::InvoiceItem.create(
			customer: self.user.stripe_user.id,
			amount: amount_to_credit.to_i,
			currency: "usd",
			description: "One-time setup fee"
		)
	end

	def calculate_duration_discount
		return nil if (not self.entered_storage_at) or self.left_storage_at

		planned_duration_discount = StorageItem.calculate_duration_discount(self.planned_duration)

		now = Time.zone.now
		entered = self.entered_storage_at
		months_since_entered_storage = (now.year - entered.year) * 12 + now.month - entered.month - (now.day >= entered.day ? 0 : 1)
		current_duration_discount = StorageItem.calculate_duration_discount(months_since_entered_storage)

		if current_duration_discount <= planned_duration_discount
			planned_duration_discount
		else
			correct_low_duration_discount(current_duration_discount, planned_duration_discount, months_since_entered_storage)
			self.planned_duration = months_since_entered_storage
			self.save
			current_duration_discount
		end
	end

	def delivery_price
		case self.item_type
		when "small"
		  return 5
		when "medium"
		  return 12
		when "large"
		  return 20
		when "extra_large"
		  return 40
		else
		  return "ERROR"
		end
	end

	def image_url
		if self.image?
			self.image.url
		else
			small_option = 'https://s3.amazonaws.com/storage_rails_app_dev/images/small-item.png'
			medium_option = 'https://s3.amazonaws.com/storage_rails_app_dev/images/med-item.png'
			large_option = 'https://s3.amazonaws.com/storage_rails_app_dev/images/large-item.png'
			extra_large_option = 'https://s3.amazonaws.com/storage_rails_app_dev/images/xlg-item.png'
			case_statement_item_types(small_option, medium_option, large_option, extra_large_option)
		end
	end

	def get_title
		if self.title.blank?
			small_option = 'Standard Box'
			medium_option = 'Medium Item'
			large_option = 'Large Item'
			extra_large_option = 'XL Item'
			case_statement_item_types(small_option, medium_option, large_option, extra_large_option)
		else
			self.title
		end
	end

	def get_description
		if self.description.blank?
			'Click "edit" to give this item a description'
		else
			self.description
		end
	end

	def rails_admin_label
		"ID: #{self.id} | USER: #{self.user.name} | TITLE: #{self.title}"
	end

	rails_admin do
		object_label_method do
			:rails_admin_label
		end
		list do
			field :id
			field :user
			field :item_type
			field :created_at
			field :updated_at
			field :image, :string do
				formatted_value do
					bindings[:view].tag(:img, {src: bindings[:object].image_url, style: 'max-height: 100px;'})
				end
			end
		end
		show do
			field :id
			field :user
			field :item_type
			field :image, :string do
				formatted_value do
					bindings[:view].tag(:img, {src: bindings[:object].image_url, style: 'max-height: 500px;'})
				end
			end
			field :title
			field :description
			field :entered_storage_at
			field :left_storage_at
			field :delivery_request
			field :pickup_request
			field :user_item_number
			field :notes
			field :storage_location
			field :discount
			field :driver
			field :planned_duration
		end
	end

	private

	def if_entered_storage_then_must_have_title_and_image
		unless self.entered_storage_at.blank?
			errors.add :title, 'must not be blank.' if self.title.blank?
			errors.add :image, 'must be present.' unless self.image?
		end
	end

	def remove_delivery_request_if_item_not_delivered
		if self.item_not_delivered == true
			self.delivery_request = nil
		end
	end

	def add_user_item_number
		User.transaction do
			user = User.lock.find(self.user_id)
			self.user_item_number = user.storage_item_number
			user.storage_item_number += 1
			user.save
		end
	end

	def case_statement_item_types(small_option, medium_option, large_option, extra_large_option)
		case self.item_type
		when 'small'
			small_option
		when 'medium'
			medium_option
		when 'large'
			large_option
		when 'extra_large'
			extra_large_option
		else
			nil
		end
	end
end

app/controllers/storage_items_controller.rb
class StorageItemsController < ApplicationController
	include ParamExtraction

	before_action :verify_user_is_ready!

	def edit
		@storage_item = StorageItem.find(params[:id])
		redirect_to new_user_session_url and return unless @storage_item.user_id == current_user.id
		@user = current_user
	end

	def update
		@storage_item = StorageItem.find(params[:id])
		redirect_to new_user_session_url and return unless @storage_item.user_id == current_user.id
		@storage_item.update(update_storage_item_params(params))
		redirect_to storage_items_url
	end

	def index
		@user = current_user


		user_pickup_requests = @user.pickup_requests.where(completion_time: nil)
		user_delivery_requests = @user.delivery_requests.where(completion_time: nil)

		@has_existing_pickup = if user_pickup_requests.count == 0 then nil else user_pickup_requests.first.id end
		@has_existing_delivery = if user_delivery_requests.count == 0 then nil else user_delivery_requests.first.id end
		@existing_delivery = user_delivery_requests.first
		@existing_pickup = user_pickup_requests.first


		# Items At Home
		@items_at_home = StorageItem.where(user_id: current_user.id, entered_storage_at: nil).count
		@boxes_at_home = StorageItem.where(user_id: current_user.id, item_type: 'small', entered_storage_at: nil)
		@medium_items_at_home = StorageItem.where(user_id: current_user.id, item_type: 'medium', entered_storage_at: nil)
		@large_items_at_home = StorageItem.where(user_id: current_user.id, item_type: 'large', entered_storage_at: nil)
		@extra_large_items_at_home = StorageItem.where(user_id: current_user.id, item_type: 'extra_large', entered_storage_at: nil)

		# Items in Storage
		@storage_items = StorageItem.where(user_id: current_user.id, left_storage_at: nil, delivery_request_id: nil).where.not(entered_storage_at: nil).order(:item_type, :entered_storage_at)


		@delivery_items = StorageItem.where(user_id: current_user.id, left_storage_at: nil).where.not(entered_storage_at: nil, delivery_request_id: nil).order(:item_type, :entered_storage_at)
		@num_delivery_items = @delivery_items.count

		@num_storage_items = @storage_items.count
		@num_boxes_in_storage = StorageItem.where(user_id: current_user.id, item_type: 'small').where.not(entered_storage_at: nil).count
		@num_medium_items_in_storage = StorageItem.where(user_id: current_user.id, item_type: 'medium').where.not(entered_storage_at: nil).count
		@num_large_items_in_storage = StorageItem.where(user_id: current_user.id, item_type: 'large').where.not(entered_storage_at: nil).count
		@num_extra_large_items_in_storage = StorageItem.where(user_id: current_user.id, item_type: 'extra_large').where.not(entered_storage_at: nil).count

		@storage_items_pending_delivery = StorageItem.where(user_id: current_user.id, left_storage_at: nil).where.not(delivery_request_id: nil, entered_storage_at: nil).order(:item_type, :entered_storage_at)

		@promo_result = if current_user.promo_code.blank?
			nil
		else
			coupon = Stripe::Coupon.retrieve(current_user.promo_code)
			coupon.amount_off / 100
		end
	end


end

app/views/storage_items/edit.html.haml
- content_for :title do
  = "Edit Storage Item |"
= render partial: 'partials/standard_header'
= render partial: "partials/blue_bar", locals:{mainText:"Edit Item", dashboard:true, faq:true}


/ Section: ITEM SELECTION
%section#edit-storage-item.home-section.text-center
  .heading-about.marginbot-20
    .container
      .row
        .col-lg-8.col-lg-offset-2
          .section-heading
            %h2.no-margin Edit Your Listing
            / %p (Give your items a description so you can easily find them in the future)
  = form_for @storage_item, :html => { multipart: true } do |form|
    .container
      .row
        .col-md-10.col-md-offset-1
          .row
            .col-md-8.col-md-offset-2.half-opacity.charges-box
              %p Upload an image or add a description to help identify your items later.
          .row
            .col-md-8.col-md-offset-2.half-opacity.charges-box
              / .single-line
              %br/
              %br/
          .row
            .col-md-4.col-md-offset-1.col-sm-4.col-xs-12.fat-white-border.boxed-grey
              .crop-mask
                - if @storage_item.image_file_name
                  = image_tag "#{@storage_item.image.url}"
                - else
                  = image_tag "https://s3.amazonaws.com/storage_rails_app_dev/images/small-item.png"
              %p Item Image
              .single-line.width-80.no-padding
              = form.file_field :image, class:"align-center"
              %br/
            .boxed-grey.col-md-6.col-sm-8.col-xs-12.fat-white-border
              #contact-form
                .row
                  .col-md-6.align-left
                    %label{:for => "name"} Name Your Item
                    = form.text_field :title, class:"form-control", placeholder: "Item Title"
                  .col-md-6.align-left
                    %label{:for => "name"} Item Id <a data-target="#itemIDModal" data-toggle = "modal" class="required_label blue pointer black-hover">&nbsp;&nbsp; Why is this important? </a>
                    = form.text_field :id, class:"form-control", disabled: true, placeholder: "test"

                  .col-md-12.align-left
                    %br/
                    %label{:for => "name"} Describe the contents
                    = form.text_area :description, placeholder:"Shoes, books, you name it!", rows:4, class:"form-control"

                .row
                  .col-md-8.col-md-offset-4.bottom-buttons.col-xs-12
                    = form.submit "Save Changes", class:"btn btn-primary pull-right loadingOnClick"
                    = link_to "Cancel", :storage_items, class:"btn gray-bg white half-opacity"

                    %p.pull-left.no-opacity p
                %br/

= render :partial => 'partials/footer'


/ Modal
#itemIDModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "itemIDModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        / %h1#itemIDModalLabel.modal-title.align-center What is the ID For?
      .modal-body.width-90
        %p.width-90
          We can storage anything. Most items fall within one of four categories. For your convenience, we've listed these categories and the items they cover below.
        %br/
        .row
          .col-md-6
            %h4.no-margin Boxes
            %ul
              %li Boxes 2' x 2' x 2' or smaller
              %li Things that fit in 2'x2'x2' boxes
          .col-md-6
            %h4.no-margin Large Items
            %ul
              %li Sofas and couches
              %li Mattresses
              %li Desks

        .row
          .col-md-6
            %h4.no-margin Medium Items
            %ul
              %li Wardrobe boxes
              %li Bicycles
              %li Sports gear (e.g. skis)
              %li Mini-fridges, lamps
              %li Coffee tables, Chairs
              %li Small Furniture
          .col-md-6
            %h4.no-margin Extra Large Items
            %ul
              %li Large dining tables
              %li Sectional couches
              %li Full bed frames
              %li Exercise equipment
              %li Items over 250lbs

      .modal-footer
        %button.btn.btn-default.pull-left{"data-dismiss" => "modal", :type => "button"} Close
        / %button.btn.btn-primary{:type => "button"} Save changes

app/views/storage_items/index.html.haml
- content_for :title do
  = "Dashboard |"
= render partial: 'partials/standard_header'
.container.full-width.blue-bg.no-padding.white.dashboard-header
  .row
    .col-md-6.col-xs-12.align-center
      .single-line.no-opacity
      %h1 HERE ARE YOUR THINGS
    .col-md-1.col-md-offset-2.col-sm-4.col-xs-4.align-center
      - if !@has_existing_pickup
        = link_to new_pickup_request_path do
          .service-box.yellow-hover
            .service-icon
              %i.fa.fa-truck
            .service-desc
              %h6
                New
                %br/
                Pickup
      - else
        = link_to edit_pickup_request_path(id: @has_existing_pickup) do
          .service-box.yellow-hover
            .service-icon
              %i.fa.fa-truck
            .service-desc
              %h6
                Edit
                %br/
                Pickup



    .col-md-1.col-sm-4.col-xs-4.align-center
      - if !@has_existing_delivery
        - if @num_storage_items < 1
          = link_to new_delivery_request_path do
            .service-box.no-pointer.half-opacity.no-hover
              .service-icon
                %i.fa.fa-home
              .service-desc
                %h6
                  Request
                  %br/
                  Delivery
        - else
          = link_to new_delivery_request_path do
            .service-box.yellow-hover
              .service-icon
                %i.fa.fa-home
              .service-desc
                %h6
                  Request
                  %br/
                  Delivery

      - else
        = link_to edit_delivery_request_path(id: @has_existing_delivery) do
          .service-box.yellow-hover
            .service-icon
              %i.fa.fa-home
            .service-desc
              %h6
                Edit
                %br/
                Delivery

%br/
%br/
%br/

// Main Body Content
.container.inventory
  .row
    .col-md-10.col-md-offset-1
      .row
        .col-md-8
          .div#storage-empty.hidden.width-90
            = link_to new_pickup_request_path do
              %img{:src => "https://s3.amazonaws.com/storage_rails_app_dev/images/nothing-in-storage.png", :alt => ""}/

          / Existing Inventory Row
          %form#delivery-form{:action => ""}
            .row
              %h2
                %span.items-count#items-in-storage #{@num_storage_items}
                Items In Storage
              .double-line
              - @storage_items.each do |storage_item|
                .col-md-6.col-sm-6.col-xs-12.inventory-entries.delivery-entry{:id => "#{storage_item.id}"}
                  .inner
                    .crop-mask
                      .crop-mask-img-wrapper
                        = image_tag(storage_item.image_url, class: "img-responsive")
                      .item-description
                        %p.subtitle.box-subtitle
                          = storage_item.get_description
                        = link_to "EDIT", {:action => "edit", "id"=>"#{storage_item.id}"}, class:"align-center description-edit-boxed heavy-font"


                    %h4.storage-item-title= storage_item.get_title
              .col-md-12.col-sm-12.col-xs-12.align-right
                %br/
            %br/

          .row#pending-delivery-form
            %h2
              %span.items-count#items-pending-delivery.hide-on-small
                %span.items-count #{@num_delivery_items}
                Items Pending Delivery
              - if @has_existing_delivery
                %p.pull-right.half-opacity.hide-on-small
                  =@existing_delivery.best_delivery_time.strftime("%B %d")
            .double-line
            - @delivery_items.each do |delivery_item|
              .col-md-6.col-sm-6.col-xs-12.inventory-entries.delivery-entry{:id => "#{delivery_item.id}"}
                .inner
                  .crop-mask
                    .crop-mask-img-wrapper
                      = image_tag(delivery_item.image_url, class: "img-responsive")
                    .item-description
                      %p.subtitle.box-subtitle
                        = delivery_item.get_description
                      = link_to "EDIT", {:action => "edit", "id"=>"#{delivery_item.id}"}, class:"align-center description-edit-boxed heavy-font"
                  %h4.storage-item-title= delivery_item.get_title
            %br/
            %br/
            %br/


          - if @has_existing_pickup
            %br/
            .row
              %h2
                Your Pickup
                - if @has_existing_pickup
                  %p.pull-right.half-opacity.hide-on-small
                    =@existing_pickup.best_delivery_time.strftime("%B %d")
              .double-line
            .row
              .col-md-12.text-block
                %br/
                %p.blue.heavy-font
                  Our driver is scheduled to arrive on
                  - if @has_existing_pickup
                    on
                    =@existing_pickup.best_delivery_time.strftime("%B %d")

                %p
                  Please make sure your items are packed before pickup.
                  Until then if you have any questions, feel free to
                  %a{:href => "mailto:team@quickbox.com"} contact us.
                  Thanks!
                %br/
            - if !@has_existing_delivery and @num_storage_items < 1
              .row
                .col-md-12.text-block.no-background
                  %br/
                  %p
                    That's all for now! You can
                    = link_to "Logout", destroy_user_session_path, method: "delete"
                    whenever you're ready.
                %br/

        .col-md-4.inventory-sidebar
          .show-on-small
            %br/
            .double-line
            %br/
          .row.text-block.light-blue-bg
            .innert
              %h5.align-center Notifications
              .single-line
              %ul
                - if @promo_result
                  %li
                    %span.order-item Successful promocode activation:
                    =@promo_result
                - if @has_existing_pickup
                  %li
                    %span.order-item You have a pickup scheduled for
                    =@existing_pickup.best_delivery_time.strftime("%B %d")
                - if @has_existing_delivery
                  %li
                    %span.order-item You have a delivery scheduled for
                    =@existing_delivery.best_delivery_time.strftime("%B %d")
                - if !@has_existing_pickup && !@has_existing_delivery
                  %li
                    %span.order-item You have no new notifications!

          .row.text-block
            .inner.align-center
              %h5 Share and Save
              %p.small-text
                / For each friend you invite to TSYN we'll take $25 off your monthly bill.
                Know a friend using storage?
                %br/
                = link_to  users_referral_path, class:"black-hover" do
                  Let them know
                about QuickBox!

          .row
            .boxed-gray.continue-button
              - if !@has_existing_pickup
                = link_to new_pickup_request_path do
                  %button#pickup-button.btn.btn-primary.gray-bg{:disabled => false, :type => "button"}
                    Request New Pickup
              - else
                = link_to edit_pickup_request_path(id: @has_existing_pickup) do
                  %button#pickup-button.btn.btn-primary.gray-bg.blue-bg-hover.no-border{:type => "button"} Edit Pickup time
              - if !@has_existing_delivery
                = link_to new_delivery_request_path do
                  %button#delivery-button.btn.btn-primary.blue-bg.blue-bg-hover{:type => "button"} Request Delivery
                / %p#delivery-subtext.light-gray.no-margin.half-opacity.pull-right
                /   (you have no items in storage)
              - else
                = link_to edit_delivery_request_path(id: @has_existing_delivery) do
                  %button#delivery-button.btn.btn-primary.blue-bg.blue-bg-hover{:type => "button"} Edit Delivery
%br/
%br/
%br/
= render partial: "partials/footer"
= render partial: "partials/aboutDeliveriesModal"



:javascript
  var numDeliveryItems = 0;
  var numPickupItems = 0;

  $(document).ready(function(){
    var atHome = parseInt(#{@items_at_home});
    var inStorage = parseInt(#{@num_storage_items});
    var pendingDelivery = parseInt(#{@storage_items_pending_delivery});
    console.log(atHome);
    console.log(inStorage);
    if (atHome == 0){
      $("#pickup-form").addClass("hidden");
    }
    if (inStorage == 0){
      $("#delivery-form").addClass("hidden");
      $("#delivery-button").parent().attr("disabled", true);
      $("#delivery-button").attr("disabled", true);
      $("#delivery-button").parent().addClass("no-pointer");
      $("#delivery-subtext").addClass("hidden");


    }
    if(pendingDelivery == 0){
      $("#pending-delivery-form").addClass("hidden");
    }
    if (atHome == 0 && inStorage == 0){
      $("#storage-empty").toggleClass("hidden");
    }

    $("#delivery-button").click(function(e){
      if (inStorage == 0){
        e.preventDefault();
      }
    });
  });